package br.com.fashionai.application.ai;

public enum AiCapability {
    PIECE_ANALYZER,
    CONTENT_MODERATOR,
    SCHEME_COMPOSER,
    DNA_SYNTHESIZER,
    BACKGROUND_GENERATOR,
    SEALBOND_MATCHER,
    STYLE_ADVISOR,
    INSIGHT_GENERATOR,
    BRAND_RESOLVER,
    COPILOT,
    STYLE_INSIGHT,
    EDIT_ASSISTANT,
    ACERVO_GROUPING,
    AFFINITY,
    THREE_D_GENERATOR,
    TRY_ON,
    TRY_ON_POLISH,
    CATEGORY_FALLBACK_COMPOSITOR,
    PHOTO_CURATOR
}
