-- GERADO por scripts/taxonomy/build_taxonomy.py a partir de scripts/taxonomy/*.py — não edite à mão.
-- Taxonomia de peças (docs/taxonomia/AUDITORIA_TAXONOMIA_PECAS.md). Só INSERT em tabelas da V38.
-- Estrutura: categorias, subcategorias (ativas e LEGACY), o que cada legado implica, dimensões e escopos.

INSERT INTO taxonomy_categories (code, display_name_pt_br, display_name_en, sort_order) VALUES
  ('upper_piece', 'Parte superior', 'Top', 1),
  ('lower_piece', 'Parte inferior', 'Bottom', 2),
  ('full_body_piece', 'Peça inteira', 'One-piece', 3),
  ('shoes_piece', 'Calçados', 'Shoes', 4),
  ('accessory_piece', 'Acessórios', 'Accessories', 5);
INSERT INTO taxonomy_subcategories (code, category_code, display_name_pt_br, display_name_en, status, replaced_by_code, sort_order) VALUES
  ('t_shirt', 'upper_piece', 'Camiseta', 'T-shirt', 'ACTIVE', NULL, 1),
  ('shirt', 'upper_piece', 'Camisa', 'Shirt', 'ACTIVE', NULL, 2),
  ('blouse', 'upper_piece', 'Blusa', 'Blouse', 'ACTIVE', NULL, 3),
  ('tank_top', 'upper_piece', 'Regata', 'Tank top', 'ACTIVE', NULL, 4),
  ('top', 'upper_piece', 'Top', 'Top', 'ACTIVE', NULL, 5),
  ('polo_shirt', 'upper_piece', 'Camisa polo', 'Polo shirt', 'ACTIVE', NULL, 7),
  ('bodysuit', 'upper_piece', 'Body', 'Bodysuit', 'ACTIVE', NULL, 8),
  ('sweater', 'upper_piece', 'Suéter', 'Sweater', 'ACTIVE', NULL, 9),
  ('sweatshirt', 'upper_piece', 'Moletom', 'Sweatshirt', 'ACTIVE', NULL, 10),
  ('hoodie', 'upper_piece', 'Moletom com capuz', 'Hoodie', 'ACTIVE', NULL, 11),
  ('cardigan', 'upper_piece', 'Cardigã', 'Cardigan', 'ACTIVE', NULL, 12),
  ('vest', 'upper_piece', 'Colete', 'Vest', 'ACTIVE', NULL, 13),
  ('blazer', 'upper_piece', 'Blazer', 'Blazer', 'ACTIVE', NULL, 14),
  ('jacket', 'upper_piece', 'Jaqueta', 'Jacket', 'ACTIVE', NULL, 15),
  ('coat', 'upper_piece', 'Casaco', 'Coat', 'ACTIVE', NULL, 16),
  ('parka', 'upper_piece', 'Parka', 'Parka', 'ACTIVE', NULL, 17),
  ('windbreaker', 'upper_piece', 'Corta-vento', 'Windbreaker', 'ACTIVE', NULL, 18),
  ('kimono', 'upper_piece', 'Quimono', 'Kimono', 'ACTIVE', NULL, 19),
  ('jeans', 'lower_piece', 'Calça jeans', 'Jeans', 'ACTIVE', NULL, 1),
  ('tailored_pants', 'lower_piece', 'Calça de alfaiataria', 'Tailored trousers', 'ACTIVE', NULL, 2),
  ('casual_pants', 'lower_piece', 'Calça casual', 'Casual pants', 'ACTIVE', NULL, 3),
  ('chino_pants', 'lower_piece', 'Calça chino', 'Chinos', 'ACTIVE', NULL, 4),
  ('cargo_pants', 'lower_piece', 'Calça cargo', 'Cargo pants', 'ACTIVE', NULL, 5),
  ('jogger_pants', 'lower_piece', 'Calça jogger', 'Joggers', 'ACTIVE', NULL, 6),
  ('sweatpants', 'lower_piece', 'Calça de moletom', 'Sweatpants', 'ACTIVE', NULL, 7),
  ('leggings', 'lower_piece', 'Legging', 'Leggings', 'ACTIVE', NULL, 8),
  ('culottes', 'lower_piece', 'Pantacourt', 'Culottes', 'ACTIVE', NULL, 9),
  ('shorts', 'lower_piece', 'Short', 'Shorts', 'ACTIVE', NULL, 10),
  ('skirt', 'lower_piece', 'Saia', 'Skirt', 'ACTIVE', NULL, 13),
  ('skort', 'lower_piece', 'Short-saia', 'Skort', 'ACTIVE', NULL, 14),
  ('dress', 'full_body_piece', 'Vestido', 'Dress', 'ACTIVE', NULL, 1),
  ('jumpsuit', 'full_body_piece', 'Macacão', 'Jumpsuit', 'ACTIVE', NULL, 2),
  ('romper', 'full_body_piece', 'Macaquinho', 'Romper', 'ACTIVE', NULL, 3),
  ('matching_set', 'full_body_piece', 'Conjunto', 'Matching set', 'ACTIVE', NULL, 4),
  ('overalls', 'full_body_piece', 'Jardineira', 'Overalls', 'ACTIVE', NULL, 5),
  ('casual_sneakers', 'shoes_piece', 'Tênis casual', 'Casual sneakers', 'ACTIVE', NULL, 1),
  ('running_shoes', 'shoes_piece', 'Tênis de corrida', 'Running shoes', 'ACTIVE', NULL, 2),
  ('training_shoes', 'shoes_piece', 'Tênis de treino', 'Training shoes', 'ACTIVE', NULL, 3),
  ('basketball_shoes', 'shoes_piece', 'Tênis de basquete', 'Basketball shoes', 'ACTIVE', NULL, 4),
  ('skate_shoes', 'shoes_piece', 'Tênis de skate', 'Skate shoes', 'ACTIVE', NULL, 5),
  ('loafers', 'shoes_piece', 'Mocassim loafer', 'Loafers', 'ACTIVE', NULL, 7),
  ('moccasins', 'shoes_piece', 'Mocassim', 'Moccasins', 'ACTIVE', NULL, 8),
  ('oxford_shoes', 'shoes_piece', 'Sapato oxford', 'Oxford shoes', 'ACTIVE', NULL, 9),
  ('derby_shoes', 'shoes_piece', 'Sapato derby', 'Derby shoes', 'ACTIVE', NULL, 10),
  ('boots', 'shoes_piece', 'Bota', 'Boots', 'ACTIVE', NULL, 11),
  ('sandals', 'shoes_piece', 'Sandália', 'Sandals', 'ACTIVE', NULL, 15),
  ('flip_flops', 'shoes_piece', 'Chinelo', 'Flip-flops', 'ACTIVE', NULL, 16),
  ('heels', 'shoes_piece', 'Salto', 'Heels', 'ACTIVE', NULL, 17),
  ('flats', 'shoes_piece', 'Sapatilha', 'Flats', 'ACTIVE', NULL, 18),
  ('espadrilles', 'shoes_piece', 'Alpargata', 'Espadrilles', 'ACTIVE', NULL, 19),
  ('handbag', 'accessory_piece', 'Bolsa de mão', 'Handbag', 'ACTIVE', NULL, 1),
  ('tote_bag', 'accessory_piece', 'Bolsa tote', 'Tote bag', 'ACTIVE', NULL, 3),
  ('clutch', 'accessory_piece', 'Clutch', 'Clutch', 'ACTIVE', NULL, 4),
  ('backpack', 'accessory_piece', 'Mochila', 'Backpack', 'ACTIVE', NULL, 5),
  ('belt', 'accessory_piece', 'Cinto', 'Belt', 'ACTIVE', NULL, 6),
  ('cap', 'accessory_piece', 'Boné', 'Cap', 'ACTIVE', NULL, 7),
  ('hat', 'accessory_piece', 'Chapéu', 'Hat', 'ACTIVE', NULL, 8),
  ('beanie', 'accessory_piece', 'Gorro', 'Beanie', 'ACTIVE', NULL, 9),
  ('scarf', 'accessory_piece', 'Cachecol', 'Scarf', 'ACTIVE', NULL, 10),
  ('tie', 'accessory_piece', 'Gravata', 'Tie', 'ACTIVE', NULL, 11),
  ('bow_tie', 'accessory_piece', 'Gravata-borboleta', 'Bow tie', 'ACTIVE', NULL, 12),
  ('sunglasses', 'accessory_piece', 'Óculos de sol', 'Sunglasses', 'ACTIVE', NULL, 13),
  ('eyeglasses', 'accessory_piece', 'Óculos de grau', 'Eyeglasses', 'ACTIVE', NULL, 14),
  ('necklace', 'accessory_piece', 'Colar', 'Necklace', 'ACTIVE', NULL, 15),
  ('bracelet', 'accessory_piece', 'Pulseira', 'Bracelet', 'ACTIVE', NULL, 16),
  ('earrings', 'accessory_piece', 'Brincos', 'Earrings', 'ACTIVE', NULL, 17),
  ('ring', 'accessory_piece', 'Anel', 'Ring', 'ACTIVE', NULL, 18),
  ('watch', 'accessory_piece', 'Relógio', 'Watch', 'ACTIVE', NULL, 19),
  ('wallet', 'accessory_piece', 'Carteira', 'Wallet', 'ACTIVE', NULL, 20),
  ('gloves', 'accessory_piece', 'Luvas', 'Gloves', 'ACTIVE', NULL, 21),
  ('socks', 'accessory_piece', 'Meias', 'Socks', 'ACTIVE', NULL, 22),
  ('hair_accessory', 'accessory_piece', 'Acessório de cabelo', 'Hair accessory', 'ACTIVE', NULL, 23);
INSERT INTO taxonomy_subcategories (code, category_code, display_name_pt_br, display_name_en, status, replaced_by_code, sort_order) VALUES
  ('crop_top', 'upper_piece', 'Cropped', 'Crop top', 'LEGACY', 'top', 6),
  ('bermuda_shorts', 'lower_piece', 'Bermuda', 'Bermuda shorts', 'LEGACY', 'shorts', 11),
  ('denim_shorts', 'lower_piece', 'Short jeans', 'Denim shorts', 'LEGACY', 'shorts', 12),
  ('high_top_sneakers', 'shoes_piece', 'Tênis cano alto', 'High-top sneakers', 'LEGACY', 'casual_sneakers', 6),
  ('ankle_boots', 'shoes_piece', 'Bota curta', 'Ankle boots', 'LEGACY', 'boots', 12),
  ('long_boots', 'shoes_piece', 'Bota cano longo', 'Knee-high boots', 'LEGACY', 'boots', 13),
  ('combat_boots', 'shoes_piece', 'Coturno', 'Combat boots', 'LEGACY', 'boots', 14),
  ('crossbody_bag', 'accessory_piece', 'Bolsa transversal', 'Crossbody bag', 'LEGACY', 'handbag', 2);
INSERT INTO taxonomy_subcategory_mappings (legacy_code, dimension_code, value_code, needs_review) VALUES
  ('crop_top', 'LENGTH', 'CROPPED', TRUE),
  ('bermuda_shorts', 'LENGTH', 'KNEE', FALSE),
  ('denim_shorts', 'MATERIAL', 'DENIM', FALSE),
  ('high_top_sneakers', 'SHAFT_HEIGHT', 'HIGH_TOP', FALSE),
  ('ankle_boots', 'SHAFT_HEIGHT', 'ANKLE', FALSE),
  ('long_boots', 'SHAFT_HEIGHT', 'KNEE_HIGH', TRUE),
  ('combat_boots', 'VARIATION', 'COMBAT', FALSE),
  ('crossbody_bag', 'CARRY_MODE', 'CROSSBODY', FALSE);
INSERT INTO taxonomy_dimensions (code, display_name_pt_br, display_name_en, multi_valued, max_per_piece, max_per_scheme, storage, sort_order) VALUES
  ('COLOR', 'Cor', 'Color', FALSE, 1, NULL, 'COLUMN', 1),
  ('MATERIAL', 'Material', 'Material', FALSE, 1, NULL, 'COLUMN', 2),
  ('PATTERN', 'Estampa', 'Pattern', FALSE, 1, NULL, 'ATTRIBUTE', 3),
  ('FINISH', 'Acabamento', 'Finish', TRUE, 3, NULL, 'ATTRIBUTE', 4),
  ('LENGTH', 'Comprimento', 'Length', FALSE, 1, NULL, 'ATTRIBUTE', 5),
  ('SHAFT_HEIGHT', 'Altura do cano', 'Shaft height', FALSE, 1, NULL, 'ATTRIBUTE', 6),
  ('RISE', 'Cintura', 'Rise', FALSE, 1, NULL, 'ATTRIBUTE', 7),
  ('HEM', 'Barra', 'Hem', FALSE, 1, NULL, 'ATTRIBUTE', 8),
  ('SLEEVE_LENGTH', 'Comprimento da manga', 'Sleeve length', FALSE, 1, NULL, 'ATTRIBUTE', 9),
  ('SLEEVE_STYLE', 'Tipo de manga', 'Sleeve style', FALSE, 1, NULL, 'ATTRIBUTE', 10),
  ('NECKLINE', 'Decote / gola', 'Neckline / collar', FALSE, 1, NULL, 'ATTRIBUTE', 11),
  ('CLOSURE', 'Fechamento', 'Closure', FALSE, 1, NULL, 'ATTRIBUTE', 12),
  ('HEEL_TYPE', 'Tipo de salto', 'Heel type', FALSE, 1, NULL, 'ATTRIBUTE', 13),
  ('HEEL_HEIGHT', 'Altura do salto', 'Heel height', FALSE, 1, NULL, 'ATTRIBUTE', 14),
  ('TOE_SHAPE', 'Bico', 'Toe shape', FALSE, 1, NULL, 'ATTRIBUTE', 15),
  ('SOLE_TYPE', 'Solado', 'Sole', FALSE, 1, NULL, 'ATTRIBUTE', 16),
  ('SPORT_USE', 'Uso / esporte', 'Sport / use', FALSE, 1, NULL, 'ATTRIBUTE', 17),
  ('CARRY_MODE', 'Forma de carregar', 'Carry mode', FALSE, 1, NULL, 'ATTRIBUTE', 18),
  ('FRAME_RIM', 'Aro', 'Rim', FALSE, 1, NULL, 'ATTRIBUTE', 19),
  ('STYLE', 'Estilo', 'Style', TRUE, 2, 3, 'ATTRIBUTE', 20),
  ('OCCASION', 'Ocasião', 'Occasion', TRUE, 2, 3, 'ATTRIBUTE', 21),
  ('GENDER', 'Gênero', 'Gender', FALSE, 1, NULL, 'COLUMN', 22),
  ('AGE_GROUP', 'Faixa etária', 'Age group', FALSE, 1, NULL, 'ATTRIBUTE', 23);
INSERT INTO taxonomy_dimension_scopes (dimension_code, category_code, subcategory_code) VALUES
  ('COLOR', 'upper_piece', ''),
  ('COLOR', 'lower_piece', ''),
  ('COLOR', 'full_body_piece', ''),
  ('COLOR', 'shoes_piece', ''),
  ('COLOR', 'accessory_piece', ''),
  ('MATERIAL', 'upper_piece', ''),
  ('MATERIAL', 'lower_piece', ''),
  ('MATERIAL', 'full_body_piece', ''),
  ('MATERIAL', 'shoes_piece', ''),
  ('MATERIAL', 'accessory_piece', ''),
  ('PATTERN', 'upper_piece', ''),
  ('PATTERN', 'lower_piece', ''),
  ('PATTERN', 'full_body_piece', ''),
  ('PATTERN', 'shoes_piece', ''),
  ('PATTERN', 'accessory_piece', ''),
  ('FINISH', 'upper_piece', ''),
  ('FINISH', 'lower_piece', ''),
  ('FINISH', 'full_body_piece', ''),
  ('FINISH', 'shoes_piece', ''),
  ('FINISH', 'accessory_piece', ''),
  ('LENGTH', 'upper_piece', ''),
  ('LENGTH', 'lower_piece', ''),
  ('LENGTH', 'full_body_piece', ''),
  ('SHAFT_HEIGHT', 'shoes_piece', ''),
  ('SHAFT_HEIGHT', 'accessory_piece', 'socks'),
  ('RISE', 'lower_piece', ''),
  ('RISE', 'full_body_piece', 'jumpsuit'),
  ('RISE', 'full_body_piece', 'romper'),
  ('RISE', 'full_body_piece', 'overalls'),
  ('HEM', 'upper_piece', ''),
  ('HEM', 'lower_piece', ''),
  ('HEM', 'full_body_piece', ''),
  ('SLEEVE_LENGTH', 'upper_piece', ''),
  ('SLEEVE_LENGTH', 'full_body_piece', ''),
  ('SLEEVE_STYLE', 'upper_piece', ''),
  ('SLEEVE_STYLE', 'full_body_piece', ''),
  ('NECKLINE', 'upper_piece', ''),
  ('NECKLINE', 'full_body_piece', ''),
  ('CLOSURE', 'upper_piece', ''),
  ('CLOSURE', 'lower_piece', ''),
  ('CLOSURE', 'full_body_piece', ''),
  ('CLOSURE', 'shoes_piece', ''),
  ('CLOSURE', 'accessory_piece', ''),
  ('HEEL_TYPE', 'shoes_piece', ''),
  ('HEEL_HEIGHT', 'shoes_piece', ''),
  ('TOE_SHAPE', 'shoes_piece', ''),
  ('SOLE_TYPE', 'shoes_piece', ''),
  ('SPORT_USE', 'upper_piece', ''),
  ('SPORT_USE', 'lower_piece', ''),
  ('SPORT_USE', 'full_body_piece', ''),
  ('SPORT_USE', 'shoes_piece', ''),
  ('SPORT_USE', 'accessory_piece', ''),
  ('CARRY_MODE', 'accessory_piece', 'handbag'),
  ('CARRY_MODE', 'accessory_piece', 'tote_bag'),
  ('CARRY_MODE', 'accessory_piece', 'clutch'),
  ('CARRY_MODE', 'accessory_piece', 'backpack'),
  ('FRAME_RIM', 'accessory_piece', 'sunglasses'),
  ('FRAME_RIM', 'accessory_piece', 'eyeglasses'),
  ('STYLE', 'upper_piece', ''),
  ('STYLE', 'lower_piece', ''),
  ('STYLE', 'full_body_piece', ''),
  ('STYLE', 'shoes_piece', ''),
  ('STYLE', 'accessory_piece', ''),
  ('OCCASION', 'upper_piece', ''),
  ('OCCASION', 'lower_piece', ''),
  ('OCCASION', 'full_body_piece', ''),
  ('OCCASION', 'shoes_piece', ''),
  ('OCCASION', 'accessory_piece', ''),
  ('GENDER', 'upper_piece', ''),
  ('GENDER', 'lower_piece', ''),
  ('GENDER', 'full_body_piece', ''),
  ('GENDER', 'shoes_piece', ''),
  ('GENDER', 'accessory_piece', ''),
  ('AGE_GROUP', 'upper_piece', ''),
  ('AGE_GROUP', 'lower_piece', ''),
  ('AGE_GROUP', 'full_body_piece', ''),
  ('AGE_GROUP', 'shoes_piece', ''),
  ('AGE_GROUP', 'accessory_piece', '');
