-- V3 — carga inicial (SEEDED) do catálogo Brand (taxonomia §brand). Marcas AUTO_DETECTED nascem só
-- pelo Brand Resolver (RF24) após regex + dedup + validação externa.
INSERT INTO brands (id, name, slug, logo_url, website, source, country, version, created_at, updated_at) VALUES
 (UUID(), 'Nike', 'nike', NULL, 'https://www.nike.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Adidas', 'adidas', NULL, 'https://www.adidas.com', 'SEEDED', 'DE', 0, NOW(6), NOW(6)),
 (UUID(), 'Zara', 'zara', NULL, 'https://www.zara.com', 'SEEDED', 'ES', 0, NOW(6), NOW(6)),
 (UUID(), 'H&M', 'h-m', NULL, 'https://www.hm.com', 'SEEDED', 'SE', 0, NOW(6), NOW(6)),
 (UUID(), 'Levi''s', 'levis', NULL, 'https://www.levi.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Farm Rio', 'farm-rio', NULL, 'https://www.farmrio.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Osklen', 'osklen', NULL, 'https://www.osklen.com', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Reserva', 'reserva', NULL, 'https://www.usereserva.com', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Hering', 'hering', NULL, 'https://www.hering.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Renner', 'renner', NULL, 'https://www.lojasrenner.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'C&A', 'c-a', NULL, 'https://www.cea.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Animale', 'animale', NULL, 'https://www.animale.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Havaianas', 'havaianas', NULL, 'https://www.havaianas.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Melissa', 'melissa', NULL, 'https://www.melissa.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Arezzo', 'arezzo', NULL, 'https://www.arezzo.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Vans', 'vans', NULL, 'https://www.vans.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Converse', 'converse', NULL, 'https://www.converse.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'New Balance', 'new-balance', NULL, 'https://www.newbalance.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Puma', 'puma', NULL, 'https://www.puma.com', 'SEEDED', 'DE', 0, NOW(6), NOW(6)),
 (UUID(), 'Lacoste', 'lacoste', NULL, 'https://www.lacoste.com', 'SEEDED', 'FR', 0, NOW(6), NOW(6)),
 (UUID(), 'Tommy Hilfiger', 'tommy-hilfiger', NULL, 'https://www.tommy.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Calvin Klein', 'calvin-klein', NULL, 'https://www.calvinklein.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Uniqlo', 'uniqlo', NULL, 'https://www.uniqlo.com', 'SEEDED', 'JP', 0, NOW(6), NOW(6)),
 (UUID(), 'Gucci', 'gucci', NULL, 'https://www.gucci.com', 'SEEDED', 'IT', 0, NOW(6), NOW(6)),
 (UUID(), 'Prada', 'prada', NULL, 'https://www.prada.com', 'SEEDED', 'IT', 0, NOW(6), NOW(6)),
 (UUID(), 'Balenciaga', 'balenciaga', NULL, 'https://www.balenciaga.com', 'SEEDED', 'FR', 0, NOW(6), NOW(6)),
 (UUID(), 'Dior', 'dior', NULL, 'https://www.dior.com', 'SEEDED', 'FR', 0, NOW(6), NOW(6)),
 (UUID(), 'Chanel', 'chanel', NULL, 'https://www.chanel.com', 'SEEDED', 'FR', 0, NOW(6), NOW(6)),
 (UUID(), 'Ralph Lauren', 'ralph-lauren', NULL, 'https://www.ralphlauren.com', 'SEEDED', 'US', 0, NOW(6), NOW(6)),
 (UUID(), 'Colcci', 'colcci', NULL, 'https://www.colcci.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Shoulder', 'shoulder', NULL, 'https://www.shoulder.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6)),
 (UUID(), 'Le Lis Blanc', 'le-lis-blanc', NULL, 'https://www.lelis.com.br', 'SEEDED', 'BR', 0, NOW(6), NOW(6));
