-- GERADO por scripts/taxonomy/build_taxonomy.py a partir de scripts/taxonomy/*.py — não edite à mão.
-- Taxonomia de peças (docs/taxonomia/AUDITORIA_TAXONOMIA_PECAS.md). Só INSERT em tabelas da V39.
-- Valores das dimensões (os atuais — cores, estilos, ocasiões, gêneros — com os mesmos códigos) e aliases de valor.

INSERT INTO taxonomy_values (dimension_code, code, display_name_pt_br, display_name_en, tier, priority, value_group, hex, scope_json, status, sort_order) VALUES
  ('COLOR', 'black', 'Preto', 'Black', 'CORE', 1, 'Preto', '#12100F', NULL, 'ACTIVE', 1),
  ('COLOR', 'charcoal', 'Grafite', 'Charcoal', 'CORE', 1, 'Preto', '#36373B', NULL, 'ACTIVE', 2),
  ('COLOR', 'washed_black', 'Preto lavado', 'Washed black', 'CORE', 1, 'Preto', '#2E2B2A', NULL, 'LEGACY', 3),
  ('COLOR', 'white', 'Branco', 'White', 'CORE', 1, 'Branco', '#FFFFFF', NULL, 'ACTIVE', 4),
  ('COLOR', 'off_white', 'Off-white', 'Off-white', 'CORE', 1, 'Branco', '#F3EFE7', NULL, 'ACTIVE', 5),
  ('COLOR', 'ivory', 'Marfim', 'Ivory', 'CORE', 1, 'Branco', '#FAF4E4', NULL, 'ACTIVE', 6),
  ('COLOR', 'cream', 'Creme', 'Cream', 'CORE', 1, 'Branco', '#F0E4CB', NULL, 'ACTIVE', 7),
  ('COLOR', 'light_gray', 'Cinza-claro', 'Light gray', 'CORE', 1, 'Cinza', '#D5D2CD', NULL, 'ACTIVE', 8),
  ('COLOR', 'gray', 'Cinza', 'Gray', 'CORE', 1, 'Cinza', '#8C8A87', NULL, 'ACTIVE', 9),
  ('COLOR', 'dark_gray', 'Cinza-escuro', 'Dark gray', 'CORE', 1, 'Cinza', '#54524F', NULL, 'ACTIVE', 10),
  ('COLOR', 'silver', 'Prata', 'Silver', 'CORE', 1, 'Cinza', '#C3C6C9', NULL, 'ACTIVE', 11),
  ('COLOR', 'blue', 'Azul', 'Blue', 'CORE', 1, 'Azul', '#2A5FA8', NULL, 'ACTIVE', 12),
  ('COLOR', 'navy', 'Azul-marinho', 'Navy', 'CORE', 1, 'Azul', '#1B2A4A', NULL, 'ACTIVE', 13),
  ('COLOR', 'light_blue', 'Azul-claro', 'Light blue', 'CORE', 1, 'Azul', '#A9C7E4', NULL, 'ACTIVE', 14),
  ('COLOR', 'sky_blue', 'Azul-céu', 'Sky blue', 'CORE', 1, 'Azul', '#7EC0E8', NULL, 'ACTIVE', 15),
  ('COLOR', 'cobalt', 'Cobalto', 'Cobalt', 'CORE', 1, 'Azul', '#0B4FC4', NULL, 'ACTIVE', 16),
  ('COLOR', 'denim', 'Jeans', 'Denim', 'CORE', 1, 'Azul', '#4A6A8C', NULL, 'LEGACY', 17),
  ('COLOR', 'teal', 'Azul-petróleo', 'Teal', 'CORE', 1, 'Azul', '#16666B', NULL, 'ACTIVE', 18),
  ('COLOR', 'red', 'Vermelho', 'Red', 'CORE', 1, 'Vermelho', '#C62B28', NULL, 'ACTIVE', 19),
  ('COLOR', 'crimson', 'Carmim', 'Crimson', 'CORE', 1, 'Vermelho', '#D6244A', NULL, 'ACTIVE', 20),
  ('COLOR', 'burgundy', 'Bordô', 'Burgundy', 'CORE', 1, 'Vermelho', '#6B1220', NULL, 'ACTIVE', 21),
  ('COLOR', 'maroon', 'Vinho', 'Maroon', 'CORE', 1, 'Vermelho', '#87313F', NULL, 'ACTIVE', 22),
  ('COLOR', 'rust', 'Ferrugem', 'Rust', 'CORE', 1, 'Vermelho', '#B05330', NULL, 'ACTIVE', 23),
  ('COLOR', 'pink', 'Rosa', 'Pink', 'CORE', 1, 'Rosa', '#EFA8BC', NULL, 'ACTIVE', 24),
  ('COLOR', 'hot_pink', 'Pink', 'Hot pink', 'CORE', 1, 'Rosa', '#E0367E', NULL, 'ACTIVE', 25),
  ('COLOR', 'rose', 'Rosé', 'Rose', 'CORE', 1, 'Rosa', '#D79A9A', NULL, 'ACTIVE', 26),
  ('COLOR', 'coral', 'Coral', 'Coral', 'CORE', 1, 'Rosa', '#F07F63', NULL, 'ACTIVE', 27),
  ('COLOR', 'salmon', 'Salmão', 'Salmon', 'CORE', 1, 'Rosa', '#F2A18B', NULL, 'ACTIVE', 28),
  ('COLOR', 'orange', 'Laranja', 'Orange', 'CORE', 1, 'Laranja', '#E8722A', NULL, 'ACTIVE', 29),
  ('COLOR', 'terracotta', 'Terracota', 'Terracotta', 'CORE', 1, 'Laranja', '#C4674A', NULL, 'ACTIVE', 30),
  ('COLOR', 'amber', 'Âmbar', 'Amber', 'CORE', 1, 'Laranja', '#D99418', NULL, 'ACTIVE', 31),
  ('COLOR', 'apricot', 'Damasco', 'Apricot', 'CORE', 1, 'Laranja', '#F2C09A', NULL, 'ACTIVE', 32),
  ('COLOR', 'yellow', 'Amarelo', 'Yellow', 'CORE', 1, 'Amarelo', '#E8C93C', NULL, 'ACTIVE', 33),
  ('COLOR', 'mustard', 'Mostarda', 'Mustard', 'CORE', 1, 'Amarelo', '#B8912A', NULL, 'ACTIVE', 34),
  ('COLOR', 'gold', 'Dourado', 'Gold', 'CORE', 1, 'Amarelo', '#C9A227', NULL, 'ACTIVE', 35),
  ('COLOR', 'butter', 'Amarelo-manteiga', 'Butter yellow', 'CORE', 1, 'Amarelo', '#F2E5A8', NULL, 'ACTIVE', 36),
  ('COLOR', 'green', 'Verde', 'Green', 'CORE', 1, 'Verde', '#2F7A45', NULL, 'ACTIVE', 37),
  ('COLOR', 'olive', 'Oliva', 'Olive', 'CORE', 1, 'Verde', '#6E7A3C', NULL, 'ACTIVE', 38),
  ('COLOR', 'military_green', 'Verde-militar', 'Military green', 'CORE', 1, 'Verde', '#4A5340', NULL, 'ACTIVE', 39),
  ('COLOR', 'forest_green', 'Verde-floresta', 'Forest green', 'CORE', 1, 'Verde', '#1C4429', NULL, 'ACTIVE', 40),
  ('COLOR', 'mint', 'Menta', 'Mint', 'CORE', 1, 'Verde', '#A9DFC2', NULL, 'ACTIVE', 41),
  ('COLOR', 'sage', 'Sálvia', 'Sage', 'CORE', 1, 'Verde', '#A3B191', NULL, 'ACTIVE', 42),
  ('COLOR', 'emerald', 'Esmeralda', 'Emerald', 'CORE', 1, 'Verde', '#187A5F', NULL, 'ACTIVE', 43),
  ('COLOR', 'purple', 'Roxo', 'Purple', 'CORE', 1, 'Roxo', '#6B3F9E', NULL, 'ACTIVE', 44),
  ('COLOR', 'violet', 'Violeta', 'Violet', 'CORE', 1, 'Roxo', '#8046D6', NULL, 'ACTIVE', 45),
  ('COLOR', 'lilac', 'Lilás', 'Lilac', 'CORE', 1, 'Roxo', '#C4A5D6', NULL, 'ACTIVE', 46),
  ('COLOR', 'lavender', 'Lavanda', 'Lavender', 'CORE', 1, 'Roxo', '#DCD5EC', NULL, 'ACTIVE', 47),
  ('COLOR', 'plum', 'Ameixa', 'Plum', 'CORE', 1, 'Roxo', '#6E3552', NULL, 'ACTIVE', 48),
  ('COLOR', 'brown', 'Marrom', 'Brown', 'CORE', 1, 'Marrom', '#5B3B28', NULL, 'ACTIVE', 49),
  ('COLOR', 'chocolate', 'Chocolate', 'Chocolate', 'CORE', 1, 'Marrom', '#4A2C1A', NULL, 'ACTIVE', 50),
  ('COLOR', 'camel', 'Caramelo', 'Camel', 'CORE', 1, 'Marrom', '#B98E5E', NULL, 'ACTIVE', 51),
  ('COLOR', 'tan', 'Castanho', 'Tan', 'CORE', 1, 'Marrom', '#C7A175', NULL, 'ACTIVE', 52),
  ('COLOR', 'beige', 'Bege', 'Beige', 'CORE', 1, 'Marrom', '#DFCDB0', NULL, 'ACTIVE', 53),
  ('COLOR', 'taupe', 'Fendi', 'Taupe', 'CORE', 1, 'Marrom', '#7A6B5D', NULL, 'ACTIVE', 54),
  ('COLOR', 'metallic_gold', 'Dourado metálico', 'Metallic gold', 'CORE', 1, 'Especiais', '#C8A64B', NULL, 'ACTIVE', 55),
  ('COLOR', 'metallic_silver', 'Prata metálico', 'Metallic silver', 'CORE', 1, 'Especiais', '#B8BCC0', NULL, 'ACTIVE', 56),
  ('COLOR', 'bronze', 'Bronze', 'Bronze', 'CORE', 1, 'Especiais', '#9C6B3C', NULL, 'ACTIVE', 57),
  ('COLOR', 'multicolor', 'Multicolorido', 'Multicolor', 'CORE', 1, 'Especiais', '#9A9A9A', NULL, 'LEGACY', 58),
  ('COLOR', 'print', 'Estampado', 'Print', 'CORE', 1, 'Especiais', '#8A8A8A', NULL, 'LEGACY', 59),
  ('MATERIAL', 'COTTON', 'Algodão', 'Cotton', 'CORE', 1, 'FIBER', NULL, NULL, 'ACTIVE', 1),
  ('MATERIAL', 'DENIM', 'Jeans (denim)', 'Denim', 'CORE', 1, 'FABRIC', NULL, NULL, 'ACTIVE', 2),
  ('MATERIAL', 'LINEN', 'Linho', 'Linen', 'CORE', 1, 'FIBER', NULL, NULL, 'ACTIVE', 3),
  ('MATERIAL', 'WOOL', 'Lã', 'Wool', 'CORE', 1, 'FIBER', NULL, NULL, 'ACTIVE', 4),
  ('MATERIAL', 'CASHMERE', 'Cashmere', 'Cashmere', 'EXTENDED', 3, 'FIBER', NULL, NULL, 'ACTIVE', 5),
  ('MATERIAL', 'SILK', 'Seda', 'Silk', 'CORE', 2, 'FIBER', NULL, NULL, 'ACTIVE', 6),
  ('MATERIAL', 'SATIN', 'Cetim', 'Satin', 'CORE', 2, 'FABRIC', NULL, NULL, 'ACTIVE', 7),
  ('MATERIAL', 'VISCOSE', 'Viscose', 'Viscose', 'CORE', 1, 'FIBER', NULL, NULL, 'ACTIVE', 8),
  ('MATERIAL', 'POLYESTER', 'Poliéster', 'Polyester', 'CORE', 1, 'FIBER', NULL, NULL, 'ACTIVE', 9),
  ('MATERIAL', 'NYLON', 'Poliamida (nylon)', 'Nylon', 'CORE', 2, 'FIBER', NULL, NULL, 'ACTIVE', 10),
  ('MATERIAL', 'ACRYLIC', 'Acrílico', 'Acrylic', 'EXTENDED', 3, 'FIBER', NULL, NULL, 'ACTIVE', 11),
  ('MATERIAL', 'FLEECE', 'Moletom / fleece', 'Fleece', 'CORE', 2, 'FABRIC', NULL, NULL, 'ACTIVE', 12),
  ('MATERIAL', 'KNIT', 'Malha / tricô', 'Knit', 'CORE', 2, 'FABRIC', NULL, NULL, 'ACTIVE', 13),
  ('MATERIAL', 'CORDUROY', 'Veludo cotelê', 'Corduroy', 'EXTENDED', 3, 'FABRIC', NULL, NULL, 'ACTIVE', 14),
  ('MATERIAL', 'VELVET', 'Veludo', 'Velvet', 'EXTENDED', 3, 'FABRIC', NULL, NULL, 'ACTIVE', 15),
  ('MATERIAL', 'CANVAS', 'Lona', 'Canvas', 'EXTENDED', 2, 'FABRIC', NULL, NULL, 'ACTIVE', 16),
  ('MATERIAL', 'MESH', 'Tela', 'Mesh', 'EXTENDED', 2, 'FABRIC', NULL, NULL, 'ACTIVE', 17),
  ('MATERIAL', 'LEATHER', 'Couro', 'Leather', 'CORE', 1, 'LEATHER', NULL, NULL, 'ACTIVE', 18),
  ('MATERIAL', 'SUEDE', 'Camurça', 'Suede', 'CORE', 2, 'LEATHER', NULL, NULL, 'ACTIVE', 19),
  ('MATERIAL', 'FAUX_LEATHER', 'Couro sintético', 'Faux leather', 'CORE', 2, 'LEATHER', NULL, NULL, 'ACTIVE', 20),
  ('MATERIAL', 'SHEARLING', 'Pelo / shearling', 'Shearling', 'EXTENDED', 3, 'LEATHER', NULL, NULL, 'ACTIVE', 21),
  ('MATERIAL', 'RUBBER', 'Borracha', 'Rubber', 'EXTENDED', 2, 'OTHER', NULL, '["shoes_piece"]', 'ACTIVE', 22),
  ('MATERIAL', 'EVA', 'EVA', 'EVA', 'EXTENDED', 2, 'OTHER', NULL, '["shoes_piece"]', 'ACTIVE', 23),
  ('MATERIAL', 'CORK', 'Cortiça', 'Cork', 'NICHE', 4, 'OTHER', NULL, '["shoes_piece", "accessory_piece"]', 'ACTIVE', 24),
  ('MATERIAL', 'STRAW', 'Palha', 'Straw', 'EXTENDED', 2, 'OTHER', NULL, '["accessory_piece", "shoes_piece"]', 'ACTIVE', 25),
  ('MATERIAL', 'METAL', 'Metal', 'Metal', 'EXTENDED', 2, 'JEWELRY', NULL, '["accessory_piece"]', 'ACTIVE', 26),
  ('MATERIAL', 'GOLD', 'Ouro', 'Gold', 'EXTENDED', 2, 'JEWELRY', NULL, '["accessory_piece"]', 'ACTIVE', 27),
  ('MATERIAL', 'SILVER', 'Prata', 'Silver', 'EXTENDED', 2, 'JEWELRY', NULL, '["accessory_piece"]', 'ACTIVE', 28),
  ('MATERIAL', 'PLATED', 'Folheado (semijoia)', 'Plated', 'EXTENDED', 2, 'JEWELRY', NULL, '["accessory_piece"]', 'ACTIVE', 29),
  ('MATERIAL', 'PEARL', 'Pérola', 'Pearl', 'NICHE', 4, 'JEWELRY', NULL, '["accessory_piece"]', 'ACTIVE', 30),
  ('MATERIAL', 'ACETATE', 'Acetato', 'Acetate', 'EXTENDED', 2, 'EYEWEAR', NULL, '["accessory_piece"]', 'ACTIVE', 31),
  ('MATERIAL', 'SYNTHETIC', 'Sintético (legado)', 'Synthetic (legacy)', 'NICHE', 5, 'LEGACY', NULL, NULL, 'LEGACY', 32),
  ('MATERIAL', 'BLEND', 'Misto (legado)', 'Blend (legacy)', 'NICHE', 5, 'LEGACY', NULL, NULL, 'LEGACY', 33),
  ('PATTERN', 'PLAIN', 'Lisa', 'Plain', 'CORE', 1, 'BASE', NULL, NULL, 'ACTIVE', 1),
  ('PATTERN', 'STRIPES', 'Listrada', 'Stripes', 'CORE', 1, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 2),
  ('PATTERN', 'PLAID', 'Xadrez', 'Plaid', 'CORE', 1, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 3),
  ('PATTERN', 'GINGHAM', 'Vichy', 'Gingham', 'EXTENDED', 2, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 4),
  ('PATTERN', 'HOUNDSTOOTH', 'Pied-de-poule', 'Houndstooth', 'EXTENDED', 3, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 5),
  ('PATTERN', 'POLKA_DOT', 'Poá', 'Polka dot', 'CORE', 2, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 6),
  ('PATTERN', 'GEOMETRIC', 'Geométrica', 'Geometric', 'EXTENDED', 2, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 7),
  ('PATTERN', 'ARGYLE', 'Argyle', 'Argyle', 'NICHE', 4, 'GEOMETRIC', NULL, NULL, 'ACTIVE', 8);
INSERT INTO taxonomy_values (dimension_code, code, display_name_pt_br, display_name_en, tier, priority, value_group, hex, scope_json, status, sort_order) VALUES
  ('PATTERN', 'FLORAL', 'Floral', 'Floral', 'CORE', 1, 'ORGANIC', NULL, NULL, 'ACTIVE', 9),
  ('PATTERN', 'TROPICAL', 'Tropical', 'Tropical', 'EXTENDED', 2, 'ORGANIC', NULL, NULL, 'ACTIVE', 10),
  ('PATTERN', 'PAISLEY', 'Paisley', 'Paisley', 'EXTENDED', 3, 'ORGANIC', NULL, NULL, 'ACTIVE', 11),
  ('PATTERN', 'ANIMAL_PRINT', 'Animal print', 'Animal print', 'CORE', 2, 'ORGANIC', NULL, NULL, 'ACTIVE', 12),
  ('PATTERN', 'CAMO', 'Camuflada', 'Camo', 'EXTENDED', 2, 'ORGANIC', NULL, NULL, 'ACTIVE', 13),
  ('PATTERN', 'TIE_DYE', 'Tie-dye', 'Tie-dye', 'EXTENDED', 2, 'ORGANIC', NULL, NULL, 'ACTIVE', 14),
  ('PATTERN', 'ABSTRACT', 'Abstrata', 'Abstract', 'EXTENDED', 3, 'ORGANIC', NULL, NULL, 'ACTIVE', 15),
  ('PATTERN', 'COLOR_BLOCK', 'Color block', 'Color block', 'EXTENDED', 2, 'GRAPHIC', NULL, NULL, 'ACTIVE', 16),
  ('PATTERN', 'GRAPHIC', 'Com estampa/arte', 'Graphic', 'CORE', 1, 'GRAPHIC', NULL, NULL, 'ACTIVE', 17),
  ('PATTERN', 'ALLOVER_LOGO', 'Logo em toda a peça', 'All-over logo', 'CORE', 2, 'LOGO', NULL, NULL, 'ACTIVE', 18),
  ('PATTERN', 'SINGLE_LOGO', 'Um logo', 'Single logo', 'CORE', 1, 'LOGO', NULL, NULL, 'ACTIVE', 19),
  ('FINISH', 'RAW', 'Cru (sem lavagem)', 'Raw', 'CORE', 2, 'WASH', NULL, NULL, 'ACTIVE', 1),
  ('FINISH', 'RINSE', 'Amaciado escuro', 'Rinse', 'EXTENDED', 3, 'WASH', NULL, NULL, 'ACTIVE', 2),
  ('FINISH', 'DARK_WASH', 'Lavagem escura', 'Dark wash', 'CORE', 1, 'WASH', NULL, NULL, 'ACTIVE', 3),
  ('FINISH', 'MEDIUM_WASH', 'Lavagem média', 'Medium wash', 'CORE', 1, 'WASH', NULL, NULL, 'ACTIVE', 4),
  ('FINISH', 'LIGHT_WASH', 'Lavagem clara', 'Light wash', 'CORE', 1, 'WASH', NULL, NULL, 'ACTIVE', 5),
  ('FINISH', 'BLEACHED', 'Delavê', 'Bleached', 'EXTENDED', 2, 'WASH', NULL, NULL, 'ACTIVE', 6),
  ('FINISH', 'STONE_WASH', 'Stonado', 'Stone wash', 'EXTENDED', 2, 'WASH', NULL, NULL, 'ACTIVE', 7),
  ('FINISH', 'ACID_WASH', 'Marmorizado', 'Acid wash', 'NICHE', 4, 'WASH', NULL, NULL, 'ACTIVE', 8),
  ('FINISH', 'FADED', 'Desbotado', 'Faded', 'EXTENDED', 2, 'WASH', NULL, NULL, 'ACTIVE', 9),
  ('FINISH', 'GARMENT_DYED', 'Tingido na peça', 'Garment dyed', 'NICHE', 4, 'WASH', NULL, NULL, 'ACTIVE', 10),
  ('FINISH', 'RIPPED', 'Destroyed', 'Ripped', 'CORE', 1, 'DISTRESS', NULL, NULL, 'ACTIVE', 11),
  ('FINISH', 'DISTRESSED', 'Puído', 'Distressed', 'EXTENDED', 2, 'DISTRESS', NULL, NULL, 'ACTIVE', 12),
  ('FINISH', 'FRAYED_HEM', 'Barra desfiada', 'Frayed hem', 'EXTENDED', 2, 'DISTRESS', NULL, NULL, 'ACTIVE', 13),
  ('FINISH', 'REPAIRED', 'Rasgo remendado', 'Repaired', 'NICHE', 5, 'DISTRESS', NULL, NULL, 'ACTIVE', 14),
  ('FINISH', 'COATED', 'Resinado', 'Coated', 'EXTENDED', 3, 'SURFACE', NULL, NULL, 'ACTIVE', 15),
  ('FINISH', 'WAXED', 'Encerado', 'Waxed', 'NICHE', 4, 'SURFACE', NULL, NULL, 'ACTIVE', 16),
  ('FINISH', 'PATENT', 'Verniz', 'Patent', 'EXTENDED', 2, 'SURFACE', NULL, '["shoes_piece", "accessory_piece"]', 'ACTIVE', 17),
  ('FINISH', 'METALLIC', 'Metalizado', 'Metallic', 'EXTENDED', 3, 'SURFACE', NULL, NULL, 'ACTIVE', 18),
  ('FINISH', 'SATIN_FINISH', 'Acetinado', 'Satin finish', 'EXTENDED', 3, 'SURFACE', NULL, NULL, 'ACTIVE', 19),
  ('FINISH', 'BRUSHED', 'Peletizado', 'Brushed', 'NICHE', 4, 'SURFACE', NULL, NULL, 'ACTIVE', 20),
  ('FINISH', 'CABLE_KNIT', 'Tricô trançado', 'Cable knit', 'EXTENDED', 2, 'TEXTURE', NULL, '["upper_piece", "full_body_piece", "accessory_piece"]', 'ACTIVE', 21),
  ('FINISH', 'RIBBED', 'Canelado', 'Ribbed', 'CORE', 2, 'TEXTURE', NULL, NULL, 'ACTIVE', 22),
  ('FINISH', 'WAFFLE', 'Waffle', 'Waffle', 'EXTENDED', 3, 'TEXTURE', NULL, NULL, 'ACTIVE', 23),
  ('FINISH', 'CHUNKY_KNIT', 'Tricô grosso', 'Chunky knit', 'EXTENDED', 3, 'TEXTURE', NULL, '["upper_piece", "accessory_piece"]', 'ACTIVE', 24),
  ('FINISH', 'POINTELLE', 'Pointelle', 'Pointelle', 'NICHE', 4, 'TEXTURE', NULL, NULL, 'ACTIVE', 25),
  ('FINISH', 'CROCHET', 'Crochê', 'Crochet', 'EXTENDED', 3, 'TEXTURE', NULL, NULL, 'ACTIVE', 26),
  ('FINISH', 'EMBROIDERED', 'Bordado', 'Embroidered', 'CORE', 2, 'EMBELLISHMENT', NULL, NULL, 'ACTIVE', 27),
  ('FINISH', 'SEQUINED', 'Paetê', 'Sequined', 'EXTENDED', 2, 'EMBELLISHMENT', NULL, NULL, 'ACTIVE', 28),
  ('FINISH', 'BEADED', 'Pedraria', 'Beaded', 'EXTENDED', 3, 'EMBELLISHMENT', NULL, NULL, 'ACTIVE', 29),
  ('FINISH', 'STUDDED', 'Tachas', 'Studded', 'EXTENDED', 3, 'EMBELLISHMENT', NULL, NULL, 'ACTIVE', 30),
  ('FINISH', 'FRINGED', 'Franjas', 'Fringed', 'EXTENDED', 3, 'EMBELLISHMENT', NULL, NULL, 'ACTIVE', 31),
  ('FINISH', 'RUFFLED', 'Babados', 'Ruffled', 'EXTENDED', 2, 'EMBELLISHMENT', NULL, NULL, 'ACTIVE', 32),
  ('LENGTH', 'CROPPED', 'Cropped', 'Cropped', 'CORE', 1, 'TOP', NULL, '["upper_piece"]', 'ACTIVE', 1),
  ('LENGTH', 'REGULAR_LENGTH', 'Comprimento regular', 'Regular length', 'CORE', 1, 'TOP', NULL, '["upper_piece"]', 'ACTIVE', 2),
  ('LENGTH', 'LONGLINE', 'Alongado', 'Longline', 'CORE', 2, 'TOP', NULL, '["upper_piece"]', 'ACTIVE', 3),
  ('LENGTH', 'MICRO', 'Micro', 'Micro', 'EXTENDED', 3, 'BOTTOM', NULL, '["lower_piece", "full_body_piece"]', 'ACTIVE', 4),
  ('LENGTH', 'MINI', 'Mini', 'Mini', 'CORE', 1, 'BOTTOM', NULL, '["lower_piece", "full_body_piece"]', 'ACTIVE', 5),
  ('LENGTH', 'MID_THIGH', 'Meio da coxa', 'Mid-thigh', 'CORE', 2, 'BOTTOM', NULL, '["upper_piece", "lower_piece", "full_body_piece"]', 'ACTIVE', 6),
  ('LENGTH', 'KNEE', 'Joelho', 'Knee', 'CORE', 1, 'BOTTOM', NULL, '["upper_piece", "lower_piece", "full_body_piece"]', 'ACTIVE', 7),
  ('LENGTH', 'MIDI', 'Midi', 'Midi', 'CORE', 1, 'BOTTOM', NULL, '["upper_piece", "lower_piece", "full_body_piece"]', 'ACTIVE', 8),
  ('LENGTH', 'MAXI', 'Longo', 'Maxi', 'CORE', 1, 'BOTTOM', NULL, '["upper_piece", "lower_piece", "full_body_piece"]', 'ACTIVE', 9),
  ('LENGTH', 'FLOOR_LENGTH', 'Até o chão', 'Floor length', 'EXTENDED', 3, 'BOTTOM', NULL, '["full_body_piece", "lower_piece"]', 'ACTIVE', 10),
  ('LENGTH', 'FULL_LENGTH', 'Comprimento total', 'Full length', 'CORE', 1, 'PANTS', NULL, '["lower_piece", "full_body_piece"]', 'ACTIVE', 11),
  ('LENGTH', 'ANKLE_LENGTH', 'Tornozelo (7/8)', 'Ankle length', 'CORE', 2, 'PANTS', NULL, '["lower_piece", "full_body_piece"]', 'ACTIVE', 12),
  ('LENGTH', 'CAPRI', 'Capri', 'Capri', 'EXTENDED', 2, 'PANTS', NULL, '["lower_piece", "full_body_piece"]', 'ACTIVE', 13),
  ('LENGTH', 'PEDAL_PUSHER', 'Corsário', 'Pedal pusher', 'NICHE', 4, 'PANTS', NULL, '["lower_piece"]', 'ACTIVE', 14),
  ('SHAFT_HEIGHT', 'LOW_TOP', 'Cano baixo', 'Low top', 'CORE', 1, 'SNEAKER', NULL, '["shoes_piece"]', 'ACTIVE', 1),
  ('SHAFT_HEIGHT', 'MID_TOP', 'Cano médio (tênis)', 'Mid top', 'CORE', 2, 'SNEAKER', NULL, '["shoes_piece"]', 'ACTIVE', 2),
  ('SHAFT_HEIGHT', 'HIGH_TOP', 'Cano alto', 'High top', 'CORE', 1, 'SNEAKER', NULL, '["shoes_piece"]', 'ACTIVE', 3),
  ('SHAFT_HEIGHT', 'NO_SHOW', 'Invisível', 'No-show', 'CORE', 2, 'SOCK', NULL, '["socks"]', 'ACTIVE', 4),
  ('SHAFT_HEIGHT', 'ANKLE', 'Tornozelo', 'Ankle', 'CORE', 1, 'BOOT_SOCK', NULL, '["shoes_piece", "socks"]', 'ACTIVE', 5),
  ('SHAFT_HEIGHT', 'QUARTER', 'Meia cano curto', 'Quarter', 'EXTENDED', 3, 'SOCK', NULL, '["socks"]', 'ACTIVE', 6),
  ('SHAFT_HEIGHT', 'CREW', 'Meia cano médio', 'Crew', 'CORE', 1, 'SOCK', NULL, '["socks"]', 'ACTIVE', 7),
  ('SHAFT_HEIGHT', 'MID_CALF', 'Meia canela', 'Mid-calf', 'CORE', 2, 'BOOT_SOCK', NULL, '["shoes_piece", "socks"]', 'ACTIVE', 8),
  ('SHAFT_HEIGHT', 'KNEE_HIGH', 'Joelho', 'Knee-high', 'CORE', 1, 'BOOT_SOCK', NULL, '["shoes_piece", "socks"]', 'ACTIVE', 9),
  ('SHAFT_HEIGHT', 'OVER_THE_KNEE', 'Acima do joelho', 'Over-the-knee', 'EXTENDED', 2, 'BOOT_SOCK', NULL, '["shoes_piece", "socks"]', 'ACTIVE', 10),
  ('SHAFT_HEIGHT', 'THIGH_HIGH', 'Coxa', 'Thigh-high', 'NICHE', 4, 'BOOT_SOCK', NULL, '["shoes_piece", "socks"]', 'ACTIVE', 11),
  ('RISE', 'LOW_RISE', 'Cintura baixa', 'Low rise', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 1),
  ('RISE', 'MID_RISE', 'Cintura média', 'Mid rise', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('RISE', 'HIGH_RISE', 'Cintura alta', 'High rise', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('RISE', 'SUPER_HIGH_RISE', 'Cintura altíssima', 'Super high rise', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 4),
  ('HEM', 'ASYMMETRIC', 'Assimétrica', 'Asymmetric', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('HEM', 'HIGH_LOW', 'Mullet', 'High-low', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 2),
  ('HEM', 'HANDKERCHIEF', 'Pontas', 'Handkerchief', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 3),
  ('HEM', 'SLIT', 'Fenda', 'Slit', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('SLEEVE_LENGTH', 'SLEEVELESS', 'Sem manga', 'Sleeveless', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('SLEEVE_LENGTH', 'SHORT_SLEEVE', 'Manga curta', 'Short sleeve', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('SLEEVE_LENGTH', 'ELBOW_SLEEVE', 'Meia manga', 'Elbow sleeve', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 3),
  ('SLEEVE_LENGTH', 'THREE_QUARTER_SLEEVE', 'Manga 3/4', 'Three-quarter sleeve', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 4),
  ('SLEEVE_LENGTH', 'LONG_SLEEVE', 'Manga longa', 'Long sleeve', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 5),
  ('SLEEVE_STYLE', 'SET_IN', 'Comum', 'Set-in', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('SLEEVE_STYLE', 'RAGLAN', 'Raglan', 'Raglan', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 2),
  ('SLEEVE_STYLE', 'DROP_SHOULDER', 'Ombro caído', 'Drop shoulder', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 3),
  ('SLEEVE_STYLE', 'DOLMAN', 'Morcego', 'Dolman', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 4),
  ('SLEEVE_STYLE', 'KIMONO_SLEEVE', 'Japonesa', 'Kimono sleeve', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 5),
  ('SLEEVE_STYLE', 'PUFF', 'Bufante', 'Puff', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 6),
  ('SLEEVE_STYLE', 'BALLOON_SLEEVE', 'Balão', 'Balloon sleeve', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 7),
  ('SLEEVE_STYLE', 'BELL', 'Sino', 'Bell', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 8),
  ('SLEEVE_STYLE', 'FLUTTER', 'Babado', 'Flutter', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 9),
  ('SLEEVE_STYLE', 'CAP_SLEEVE', 'Cavada curtinha', 'Cap sleeve', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 10),
  ('NECKLINE', 'CREW', 'Careca', 'Crew', 'CORE', 1, 'NECK', NULL, NULL, 'ACTIVE', 1),
  ('NECKLINE', 'V_NECK', 'Decote V', 'V-neck', 'CORE', 1, 'NECK', NULL, NULL, 'ACTIVE', 2),
  ('NECKLINE', 'SCOOP', 'Decote U', 'Scoop', 'EXTENDED', 2, 'NECK', NULL, NULL, 'ACTIVE', 3),
  ('NECKLINE', 'BOAT', 'Canoa', 'Boat', 'EXTENDED', 2, 'NECK', NULL, NULL, 'ACTIVE', 4),
  ('NECKLINE', 'SQUARE_NECK', 'Quadrado', 'Square', 'EXTENDED', 2, 'NECK', NULL, NULL, 'ACTIVE', 5),
  ('NECKLINE', 'SWEETHEART', 'Coração', 'Sweetheart', 'EXTENDED', 3, 'NECK', NULL, NULL, 'ACTIVE', 6),
  ('NECKLINE', 'PLUNGE', 'Profundo', 'Plunge', 'EXTENDED', 3, 'NECK', NULL, NULL, 'ACTIVE', 7),
  ('NECKLINE', 'OFF_SHOULDER', 'Ombro a ombro', 'Off-shoulder', 'CORE', 2, 'NECK', NULL, NULL, 'ACTIVE', 8),
  ('NECKLINE', 'ONE_SHOULDER', 'Um ombro só', 'One-shoulder', 'EXTENDED', 2, 'NECK', NULL, NULL, 'ACTIVE', 9);
INSERT INTO taxonomy_values (dimension_code, code, display_name_pt_br, display_name_en, tier, priority, value_group, hex, scope_json, status, sort_order) VALUES
  ('NECKLINE', 'HALTER', 'Frente única', 'Halter', 'CORE', 2, 'NECK', NULL, NULL, 'ACTIVE', 10),
  ('NECKLINE', 'STRAPLESS', 'Tomara que caia', 'Strapless', 'CORE', 2, 'NECK', NULL, NULL, 'ACTIVE', 11),
  ('NECKLINE', 'COWL', 'Drapeado', 'Cowl', 'EXTENDED', 3, 'NECK', NULL, NULL, 'ACTIVE', 12),
  ('NECKLINE', 'KEYHOLE', 'Gota', 'Keyhole', 'NICHE', 4, 'NECK', NULL, NULL, 'ACTIVE', 13),
  ('NECKLINE', 'TURTLENECK', 'Gola alta', 'Turtleneck', 'CORE', 1, 'COLLAR', NULL, NULL, 'ACTIVE', 14),
  ('NECKLINE', 'MOCK_NECK', 'Gola média', 'Mock neck', 'EXTENDED', 2, 'COLLAR', NULL, NULL, 'ACTIVE', 15),
  ('NECKLINE', 'HENLEY', 'Portinhola', 'Henley', 'EXTENDED', 2, 'COLLAR', NULL, NULL, 'ACTIVE', 16),
  ('NECKLINE', 'POLO_COLLAR', 'Gola polo', 'Polo collar', 'CORE', 2, 'COLLAR', NULL, NULL, 'ACTIVE', 17),
  ('NECKLINE', 'SHIRT_COLLAR', 'Colarinho', 'Shirt collar', 'CORE', 1, 'COLLAR', NULL, NULL, 'ACTIVE', 18),
  ('NECKLINE', 'BUTTON_DOWN_COLLAR', 'Button-down', 'Button-down', 'EXTENDED', 2, 'COLLAR', NULL, NULL, 'ACTIVE', 19),
  ('NECKLINE', 'MANDARIN', 'Gola padre', 'Mandarin', 'EXTENDED', 2, 'COLLAR', NULL, NULL, 'ACTIVE', 20),
  ('NECKLINE', 'CAMP_COLLAR', 'Gola cubana', 'Camp collar', 'EXTENDED', 3, 'COLLAR', NULL, NULL, 'ACTIVE', 21),
  ('NECKLINE', 'PETER_PAN', 'Gola boneca', 'Peter Pan', 'EXTENDED', 3, 'COLLAR', NULL, NULL, 'ACTIVE', 22),
  ('NECKLINE', 'BOW_COLLAR', 'Gola laço', 'Bow', 'EXTENDED', 3, 'COLLAR', NULL, NULL, 'ACTIVE', 23),
  ('NECKLINE', 'HOOD', 'Capuz', 'Hood', 'CORE', 1, 'COLLAR', NULL, NULL, 'ACTIVE', 24),
  ('NECKLINE', 'NOTCH_LAPEL', 'Lapela tradicional', 'Notch lapel', 'EXTENDED', 2, 'LAPEL', NULL, NULL, 'ACTIVE', 25),
  ('NECKLINE', 'PEAK_LAPEL', 'Lapela pontiaguda', 'Peak lapel', 'EXTENDED', 3, 'LAPEL', NULL, NULL, 'ACTIVE', 26),
  ('NECKLINE', 'SHAWL_LAPEL', 'Gola xale', 'Shawl lapel', 'EXTENDED', 3, 'LAPEL', NULL, NULL, 'ACTIVE', 27),
  ('CLOSURE', 'PULLOVER', 'Sem fechamento (vestir pela cabeça)', 'Pullover', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('CLOSURE', 'BUTTON', 'Botões', 'Button', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('CLOSURE', 'SNAP', 'Botão de pressão', 'Snap', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 3),
  ('CLOSURE', 'ZIPPER', 'Zíper', 'Zipper', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('CLOSURE', 'HALF_ZIP', 'Meio zíper', 'Half-zip', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 5),
  ('CLOSURE', 'SINGLE_BREASTED', 'Abotoamento simples', 'Single-breasted', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 6),
  ('CLOSURE', 'DOUBLE_BREASTED', 'Transpassado', 'Double-breasted', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 7),
  ('CLOSURE', 'HOOK_AND_EYE', 'Colchete', 'Hook and eye', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 8),
  ('CLOSURE', 'TIE', 'Amarração', 'Tie', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 9),
  ('CLOSURE', 'DRAWSTRING', 'Cordão', 'Drawstring', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 10),
  ('CLOSURE', 'ELASTIC', 'Elástico', 'Elastic', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 11),
  ('CLOSURE', 'LACE_UP', 'Cadarço', 'Lace-up', 'CORE', 1, NULL, NULL, '["shoes_piece"]', 'ACTIVE', 12),
  ('CLOSURE', 'SLIP_ON', 'Calce fácil', 'Slip-on', 'CORE', 1, NULL, NULL, '["shoes_piece"]', 'ACTIVE', 13),
  ('CLOSURE', 'VELCRO', 'Velcro', 'Hook and loop', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 14),
  ('CLOSURE', 'BUCKLE', 'Fivela', 'Buckle', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 15),
  ('CLOSURE', 'MAGNETIC', 'Ímã', 'Magnetic', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 16),
  ('CLOSURE', 'TOGGLE', 'Pino (toggle)', 'Toggle', 'NICHE', 4, NULL, NULL, NULL, 'ACTIVE', 17),
  ('CLOSURE', 'FLAP', 'Aba', 'Flap', 'CORE', 2, NULL, NULL, '["accessory_piece"]', 'ACTIVE', 18),
  ('CLOSURE', 'OPEN_TOP', 'Aberta', 'Open top', 'EXTENDED', 2, NULL, NULL, '["accessory_piece"]', 'ACTIVE', 19),
  ('CLOSURE', 'CLASP', 'Fecho de joia', 'Clasp', 'EXTENDED', 2, NULL, NULL, '["accessory_piece"]', 'ACTIVE', 20),
  ('CLOSURE', 'CLIP_ON', 'Pressão sem furo', 'Clip-on', 'EXTENDED', 3, NULL, NULL, '["accessory_piece"]', 'ACTIVE', 21),
  ('HEEL_TYPE', 'STILETTO', 'Agulha', 'Stiletto', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('HEEL_TYPE', 'BLOCK', 'Bloco', 'Block', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('HEEL_TYPE', 'KITTEN', 'Gatinho', 'Kitten', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 3),
  ('HEEL_TYPE', 'WEDGE', 'Anabela', 'Wedge', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('HEEL_TYPE', 'CONE', 'Cone', 'Cone', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 5),
  ('HEEL_TYPE', 'SPOOL', 'Carretel', 'Spool', 'NICHE', 4, NULL, NULL, NULL, 'ACTIVE', 6),
  ('HEEL_TYPE', 'CUBAN', 'Cubano', 'Cuban', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 7),
  ('HEEL_TYPE', 'SCULPTURAL', 'Escultural', 'Sculptural', 'NICHE', 4, NULL, NULL, NULL, 'ACTIVE', 8),
  ('HEEL_HEIGHT', 'FLAT', 'Rasteiro (0–1,2 cm)', 'Flat', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('HEEL_HEIGHT', 'LOW', 'Baixo (2,5–6 cm)', 'Low', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('HEEL_HEIGHT', 'MID', 'Médio (6–8,5 cm)', 'Mid', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('HEEL_HEIGHT', 'HIGH', 'Alto (8,5–10 cm)', 'High', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('HEEL_HEIGHT', 'VERY_HIGH', 'Altíssimo (> 10 cm)', 'Very high', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 5),
  ('TOE_SHAPE', 'ROUND_TOE', 'Redondo', 'Round', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('TOE_SHAPE', 'ALMOND_TOE', 'Amendoado', 'Almond', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 2),
  ('TOE_SHAPE', 'POINTED_TOE', 'Bico fino', 'Pointed', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('TOE_SHAPE', 'SQUARE_TOE', 'Bico quadrado', 'Square', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 4),
  ('TOE_SHAPE', 'PEEP_TOE', 'Peep toe', 'Peep toe', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 5),
  ('TOE_SHAPE', 'OPEN_TOE', 'Aberto', 'Open toe', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 6),
  ('SOLE_TYPE', 'PLATFORM', 'Plataforma', 'Platform', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('SOLE_TYPE', 'FRONT_PLATFORM', 'Meia pata', 'Front platform', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 2),
  ('SOLE_TYPE', 'FLATFORM', 'Flatform', 'Flatform', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 3),
  ('SOLE_TYPE', 'LUG', 'Tratorado', 'Lug', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('SPORT_USE', 'LIFESTYLE', 'Casual / lifestyle', 'Lifestyle', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('SPORT_USE', 'RUNNING', 'Corrida', 'Running', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('SPORT_USE', 'TRAINING', 'Treino / academia', 'Training', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('SPORT_USE', 'BASKETBALL', 'Basquete', 'Basketball', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 4),
  ('SPORT_USE', 'SKATE', 'Skate', 'Skateboarding', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 5),
  ('SPORT_USE', 'FOOTBALL', 'Futebol', 'Football', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 6),
  ('SPORT_USE', 'TENNIS', 'Tênis / padel', 'Tennis', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 7),
  ('SPORT_USE', 'VOLLEYBALL', 'Vôlei', 'Volleyball', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 8),
  ('SPORT_USE', 'CYCLING', 'Ciclismo', 'Cycling', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 9),
  ('SPORT_USE', 'SWIM_SURF', 'Natação / surf', 'Swim / surf', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 10),
  ('SPORT_USE', 'HIKING', 'Trilha / outdoor', 'Hiking', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 11),
  ('SPORT_USE', 'YOGA_PILATES', 'Yoga / pilates', 'Yoga / pilates', 'EXTENDED', 2, NULL, NULL, NULL, 'ACTIVE', 12),
  ('SPORT_USE', 'DANCE', 'Dança', 'Dance', 'NICHE', 4, NULL, NULL, NULL, 'ACTIVE', 13),
  ('SPORT_USE', 'COMBAT_SPORTS', 'Lutas', 'Combat sports', 'NICHE', 4, NULL, NULL, NULL, 'ACTIVE', 14),
  ('SPORT_USE', 'GOLF', 'Golfe', 'Golf', 'NICHE', 5, NULL, NULL, NULL, 'ACTIVE', 15),
  ('CARRY_MODE', 'HAND', 'Mão', 'Hand', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('CARRY_MODE', 'SHOULDER', 'Ombro', 'Shoulder', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('CARRY_MODE', 'CROSSBODY', 'Transversal', 'Crossbody', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('CARRY_MODE', 'WAIST', 'Cintura', 'Waist', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 4),
  ('CARRY_MODE', 'BACK', 'Costas', 'Back', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 5),
  ('CARRY_MODE', 'WRIST', 'Pulso', 'Wrist', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 6),
  ('FRAME_RIM', 'FULL_RIM', 'Aro fechado', 'Full rim', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('FRAME_RIM', 'SEMI_RIMLESS', 'Fio de nylon', 'Semi-rimless', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 2),
  ('FRAME_RIM', 'RIMLESS', 'Sem aro', 'Rimless', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 3),
  ('STYLE', 'classic', 'Clássico', 'Classic', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('STYLE', 'minimalist', 'Minimalista', 'Minimalist', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('STYLE', 'modern', 'Moderno', 'Modern', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('STYLE', 'chic', 'Chique', 'Chic', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('STYLE', 'streetwear', 'Streetwear', 'Streetwear', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 5),
  ('STYLE', 'sporty', 'Esportivo', 'Sporty', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 6),
  ('STYLE', 'athleisure', 'Athleisure', 'Athleisure', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 7),
  ('STYLE', 'preppy', 'Preppy', 'Preppy', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 8),
  ('STYLE', 'romantic', 'Romântico', 'Romantic', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 9),
  ('STYLE', 'boho', 'Boho', 'Boho', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 10),
  ('STYLE', 'vintage', 'Vintage', 'Vintage', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 11),
  ('STYLE', 'grunge', 'Grunge', 'Grunge', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 12),
  ('STYLE', 'edgy', 'Ousado', 'Edgy', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 13),
  ('STYLE', 'glam', 'Glam', 'Glam', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 14);
INSERT INTO taxonomy_values (dimension_code, code, display_name_pt_br, display_name_en, tier, priority, value_group, hex, scope_json, status, sort_order) VALUES
  ('STYLE', 'luxury', 'Luxo', 'Luxury', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 15),
  ('STYLE', 'avant_garde', 'Vanguarda', 'Avant-garde', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 16),
  ('STYLE', 'y2k', 'Y2K', 'Y2K', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 17),
  ('STYLE', 'utility', 'Utilitário', 'Utility', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 18),
  ('STYLE', 'techwear', 'Techwear', 'Techwear', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 19),
  ('STYLE', 'tailored', 'Alfaiataria', 'Tailored', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 20),
  ('STYLE', 'urban', 'Urbano', 'Urban', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 21),
  ('STYLE', 'resort', 'Resort', 'Resort', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 22),
  ('STYLE', 'basic', 'Básico', 'Basic', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 23),
  ('STYLE', 'statement', 'Marcante', 'Statement', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 24),
  ('STYLE', 'futuristic', 'Futurista', 'Futuristic', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 25),
  ('OCCASION', 'casual', 'Casual', 'Casual', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('OCCASION', 'work', 'Trabalho', 'Work', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('OCCASION', 'business', 'Negócios', 'Business', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('OCCASION', 'formal', 'Formal', 'Formal', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 4),
  ('OCCASION', 'party', 'Festa', 'Party', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 5),
  ('OCCASION', 'night_out', 'Noite', 'Night out', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 6),
  ('OCCASION', 'date', 'Encontro', 'Date', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 7),
  ('OCCASION', 'wedding', 'Casamento', 'Wedding', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 8),
  ('OCCASION', 'ceremony', 'Cerimônia', 'Ceremony', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 9),
  ('OCCASION', 'sport', 'Esporte', 'Sport', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 10),
  ('OCCASION', 'gym', 'Academia', 'Gym', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 11),
  ('OCCASION', 'travel', 'Viagem', 'Travel', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 12),
  ('OCCASION', 'beach', 'Praia', 'Beach', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 13),
  ('OCCASION', 'vacation', 'Férias', 'Vacation', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 14),
  ('OCCASION', 'school', 'Escola', 'School', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 15),
  ('OCCASION', 'university', 'Faculdade', 'College', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 16),
  ('OCCASION', 'social', 'Social', 'Social', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 17),
  ('OCCASION', 'home', 'Casa', 'Home', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 18),
  ('OCCASION', 'outdoor', 'Ao ar livre', 'Outdoor', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 19),
  ('OCCASION', 'festival', 'Festival', 'Festival', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 20),
  ('GENDER', 'MASCULINO', 'Masculino', 'Men''s', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('GENDER', 'FEMININO', 'Feminino', 'Women''s', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 2),
  ('GENDER', 'UNISSEX', 'Unissex', 'Unisex', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('AGE_GROUP', 'ADULT', 'Adulto', 'Adult', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 1),
  ('AGE_GROUP', 'TEEN', 'Juvenil', 'Teen', 'EXTENDED', 3, NULL, NULL, NULL, 'ACTIVE', 2),
  ('AGE_GROUP', 'KIDS', 'Infantil', 'Kids', 'CORE', 1, NULL, NULL, NULL, 'ACTIVE', 3),
  ('AGE_GROUP', 'BABY', 'Bebê', 'Baby', 'CORE', 2, NULL, NULL, NULL, 'ACTIVE', 4);
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'COLOR', 'black', '', 'preto', 'preto', 'pt-BR'),
  ('VALUE', 'COLOR', 'black', '', 'preta', 'preta', 'pt-BR'),
  ('VALUE', 'COLOR', 'black', '', 'negro', 'negro', 'pt-BR'),
  ('VALUE', 'COLOR', 'black', '', 'negra', 'negra', 'pt-BR'),
  ('VALUE', 'COLOR', 'black', '', 'noir', 'noir', 'pt-BR'),
  ('VALUE', 'COLOR', 'charcoal', '', 'grafite', 'grafite', 'pt-BR'),
  ('VALUE', 'COLOR', 'charcoal', '', 'carvao', 'carvao', 'pt-BR'),
  ('VALUE', 'COLOR', 'white', '', 'branco', 'branco', 'pt-BR'),
  ('VALUE', 'COLOR', 'white', '', 'branca', 'branca', 'pt-BR'),
  ('VALUE', 'COLOR', 'white', '', 'blanco', 'blanco', 'pt-BR'),
  ('VALUE', 'COLOR', 'white', '', 'blanca', 'blanca', 'pt-BR'),
  ('VALUE', 'COLOR', 'white', '', 'blanc', 'blanc', 'pt-BR'),
  ('VALUE', 'COLOR', 'off_white', '', 'offwhite', 'offwhite', 'pt-BR'),
  ('VALUE', 'COLOR', 'off_white', '', 'gelo', 'gelo', 'pt-BR'),
  ('VALUE', 'COLOR', 'ivory', '', 'marfim', 'marfim', 'pt-BR'),
  ('VALUE', 'COLOR', 'cream', '', 'creme', 'creme', 'pt-BR'),
  ('VALUE', 'COLOR', 'cream', '', 'cru', 'cru', 'pt-BR'),
  ('VALUE', 'COLOR', 'cream', '', 'sail', 'sail', 'pt-BR'),
  ('VALUE', 'COLOR', 'light_gray', '', 'light grey', 'light grey', 'pt-BR'),
  ('VALUE', 'COLOR', 'light_gray', '', 'cinza claro', 'cinza claro', 'pt-BR'),
  ('VALUE', 'COLOR', 'light_gray', '', 'mescla', 'mescla', 'pt-BR'),
  ('VALUE', 'COLOR', 'gray', '', 'grey', 'grey', 'pt-BR'),
  ('VALUE', 'COLOR', 'gray', '', 'cinza', 'cinza', 'pt-BR'),
  ('VALUE', 'COLOR', 'gray', '', 'gris', 'gris', 'pt-BR'),
  ('VALUE', 'COLOR', 'dark_gray', '', 'dark grey', 'dark grey', 'pt-BR'),
  ('VALUE', 'COLOR', 'dark_gray', '', 'cinza escuro', 'cinza escuro', 'pt-BR'),
  ('VALUE', 'COLOR', 'dark_gray', '', 'chumbo', 'chumbo', 'pt-BR'),
  ('VALUE', 'COLOR', 'silver', '', 'prata', 'prata', 'pt-BR'),
  ('VALUE', 'COLOR', 'silver', '', 'prateado', 'prateado', 'pt-BR'),
  ('VALUE', 'COLOR', 'blue', '', 'azul', 'azul', 'pt-BR'),
  ('VALUE', 'COLOR', 'navy', '', 'marinho', 'marinho', 'pt-BR'),
  ('VALUE', 'COLOR', 'navy', '', 'azul marinho', 'azul marinho', 'pt-BR'),
  ('VALUE', 'COLOR', 'navy', '', 'dark navy', 'dark navy', 'pt-BR'),
  ('VALUE', 'COLOR', 'light_blue', '', 'azul claro', 'azul claro', 'pt-BR'),
  ('VALUE', 'COLOR', 'light_blue', '', 'azul bebe', 'azul bebe', 'pt-BR'),
  ('VALUE', 'COLOR', 'sky_blue', '', 'azul celeste', 'azul celeste', 'pt-BR'),
  ('VALUE', 'COLOR', 'sky_blue', '', 'celeste', 'celeste', 'pt-BR'),
  ('VALUE', 'COLOR', 'cobalt', '', 'azul royal', 'azul royal', 'pt-BR'),
  ('VALUE', 'COLOR', 'cobalt', '', 'royal blue', 'royal blue', 'pt-BR'),
  ('VALUE', 'COLOR', 'cobalt', '', 'royal', 'royal', 'pt-BR'),
  ('VALUE', 'COLOR', 'denim', '', 'indigo', 'indigo', 'pt-BR'),
  ('VALUE', 'COLOR', 'denim', '', 'jeans', 'jeans', 'pt-BR'),
  ('VALUE', 'COLOR', 'denim', '', 'stonewash', 'stonewash', 'pt-BR'),
  ('VALUE', 'COLOR', 'denim', '', 'medium wash', 'medium wash', 'pt-BR'),
  ('VALUE', 'COLOR', 'denim', '', 'dark wash', 'dark wash', 'pt-BR'),
  ('VALUE', 'COLOR', 'denim', '', 'light wash', 'light wash', 'pt-BR'),
  ('VALUE', 'COLOR', 'teal', '', 'azul petroleo', 'azul petroleo', 'pt-BR'),
  ('VALUE', 'COLOR', 'teal', '', 'petroleo', 'petroleo', 'pt-BR'),
  ('VALUE', 'COLOR', 'red', '', 'vermelho', 'vermelho', 'pt-BR'),
  ('VALUE', 'COLOR', 'red', '', 'vermelha', 'vermelha', 'pt-BR'),
  ('VALUE', 'COLOR', 'red', '', 'rojo', 'rojo', 'pt-BR'),
  ('VALUE', 'COLOR', 'red', '', 'rouge', 'rouge', 'pt-BR'),
  ('VALUE', 'COLOR', 'crimson', '', 'carmim', 'carmim', 'pt-BR'),
  ('VALUE', 'COLOR', 'burgundy', '', 'bordo', 'bordo', 'pt-BR'),
  ('VALUE', 'COLOR', 'burgundy', '', 'vinho', 'vinho', 'pt-BR'),
  ('VALUE', 'COLOR', 'burgundy', '', 'wine', 'wine', 'pt-BR'),
  ('VALUE', 'COLOR', 'maroon', '', 'marsala', 'marsala', 'pt-BR'),
  ('VALUE', 'COLOR', 'rust', '', 'ferrugem', 'ferrugem', 'pt-BR'),
  ('VALUE', 'COLOR', 'pink', '', 'rosa', 'rosa', 'pt-BR'),
  ('VALUE', 'COLOR', 'pink', '', 'rose pink', 'rose pink', 'pt-BR'),
  ('VALUE', 'COLOR', 'hot_pink', '', 'pink choque', 'pink choque', 'pt-BR'),
  ('VALUE', 'COLOR', 'hot_pink', '', 'rosa choque', 'rosa choque', 'pt-BR'),
  ('VALUE', 'COLOR', 'hot_pink', '', 'fuchsia', 'fuchsia', 'pt-BR'),
  ('VALUE', 'COLOR', 'hot_pink', '', 'fucsia', 'fucsia', 'pt-BR'),
  ('VALUE', 'COLOR', 'salmon', '', 'salmao', 'salmao', 'pt-BR'),
  ('VALUE', 'COLOR', 'orange', '', 'laranja', 'laranja', 'pt-BR'),
  ('VALUE', 'COLOR', 'orange', '', 'naranja', 'naranja', 'pt-BR'),
  ('VALUE', 'COLOR', 'terracotta', '', 'terracota', 'terracota', 'pt-BR'),
  ('VALUE', 'COLOR', 'yellow', '', 'amarelo', 'amarelo', 'pt-BR'),
  ('VALUE', 'COLOR', 'yellow', '', 'amarela', 'amarela', 'pt-BR'),
  ('VALUE', 'COLOR', 'yellow', '', 'amarillo', 'amarillo', 'pt-BR'),
  ('VALUE', 'COLOR', 'mustard', '', 'mostarda', 'mostarda', 'pt-BR'),
  ('VALUE', 'COLOR', 'gold', '', 'dourado', 'dourado', 'pt-BR'),
  ('VALUE', 'COLOR', 'gold', '', 'dourada', 'dourada', 'pt-BR'),
  ('VALUE', 'COLOR', 'green', '', 'verde', 'verde', 'pt-BR'),
  ('VALUE', 'COLOR', 'green', '', 'vert', 'vert', 'pt-BR'),
  ('VALUE', 'COLOR', 'olive', '', 'oliva', 'oliva', 'pt-BR'),
  ('VALUE', 'COLOR', 'olive', '', 'verde oliva', 'verde oliva', 'pt-BR'),
  ('VALUE', 'COLOR', 'military_green', '', 'verde militar', 'verde militar', 'pt-BR'),
  ('VALUE', 'COLOR', 'military_green', '', 'army green', 'army green', 'pt-BR'),
  ('VALUE', 'COLOR', 'military_green', '', 'khaki green', 'khaki green', 'pt-BR'),
  ('VALUE', 'COLOR', 'forest_green', '', 'verde floresta', 'verde floresta', 'pt-BR'),
  ('VALUE', 'COLOR', 'forest_green', '', 'verde escuro', 'verde escuro', 'pt-BR'),
  ('VALUE', 'COLOR', 'forest_green', '', 'dark green', 'dark green', 'pt-BR'),
  ('VALUE', 'COLOR', 'mint', '', 'menta', 'menta', 'pt-BR'),
  ('VALUE', 'COLOR', 'mint', '', 'verde menta', 'verde menta', 'pt-BR'),
  ('VALUE', 'COLOR', 'sage', '', 'verde salvia', 'verde salvia', 'pt-BR'),
  ('VALUE', 'COLOR', 'emerald', '', 'esmeralda', 'esmeralda', 'pt-BR'),
  ('VALUE', 'COLOR', 'emerald', '', 'verde esmeralda', 'verde esmeralda', 'pt-BR'),
  ('VALUE', 'COLOR', 'purple', '', 'roxo', 'roxo', 'pt-BR'),
  ('VALUE', 'COLOR', 'purple', '', 'roxa', 'roxa', 'pt-BR'),
  ('VALUE', 'COLOR', 'purple', '', 'morado', 'morado', 'pt-BR'),
  ('VALUE', 'COLOR', 'violet', '', 'violeta', 'violeta', 'pt-BR'),
  ('VALUE', 'COLOR', 'lilac', '', 'lilas', 'lilas', 'pt-BR'),
  ('VALUE', 'COLOR', 'lavender', '', 'lavanda', 'lavanda', 'pt-BR'),
  ('VALUE', 'COLOR', 'plum', '', 'ameixa', 'ameixa', 'pt-BR'),
  ('VALUE', 'COLOR', 'brown', '', 'marrom', 'marrom', 'pt-BR'),
  ('VALUE', 'COLOR', 'brown', '', 'marron', 'marron', 'pt-BR'),
  ('VALUE', 'COLOR', 'brown', '', 'castanho', 'castanho', 'pt-BR'),
  ('VALUE', 'COLOR', 'camel', '', 'caramelo', 'caramelo', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'COLOR', 'tan', '', 'wheat', 'wheat', 'pt-BR'),
  ('VALUE', 'COLOR', 'tan', '', 'whisky', 'whisky', 'pt-BR'),
  ('VALUE', 'COLOR', 'beige', '', 'bege', 'bege', 'pt-BR'),
  ('VALUE', 'COLOR', 'beige', '', 'nude', 'nude', 'pt-BR'),
  ('VALUE', 'COLOR', 'beige', '', 'areia', 'areia', 'pt-BR'),
  ('VALUE', 'COLOR', 'beige', '', 'sand', 'sand', 'pt-BR'),
  ('VALUE', 'COLOR', 'beige', '', 'khaki', 'khaki', 'pt-BR'),
  ('VALUE', 'COLOR', 'beige', '', 'caqui', 'caqui', 'pt-BR'),
  ('VALUE', 'COLOR', 'taupe', '', 'fendi', 'fendi', 'pt-BR'),
  ('VALUE', 'COLOR', 'multicolor', '', 'multicolorido', 'multicolorido', 'pt-BR'),
  ('VALUE', 'COLOR', 'multicolor', '', 'colorido', 'colorido', 'pt-BR'),
  ('VALUE', 'COLOR', 'multicolor', '', 'multi', 'multi', 'pt-BR'),
  ('VALUE', 'COLOR', 'print', '', 'estampado', 'estampado', 'pt-BR'),
  ('VALUE', 'COLOR', 'print', '', 'estampa', 'estampa', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'COTTON', '', 'algodão', 'algodao', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'COTTON', '', 'piquet', 'piquet', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'COTTON', '', 'jersey', 'jersey', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'COTTON', '', 'sarja', 'sarja', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'COTTON', '', 'twill', 'twill', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'DENIM', '', 'jeans', 'jeans', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'DENIM', '', 'índigo', 'indigo', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'LINEN', '', 'linho', 'linho', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'WOOL', '', 'lã', 'la', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'WOOL', '', 'merino', 'merino', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'WOOL', '', 'lã batida', 'la batida', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'CASHMERE', '', 'caxemira', 'caxemira', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SILK', '', 'seda', 'seda', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SATIN', '', 'cetim', 'cetim', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'VISCOSE', '', 'rayon', 'rayon', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'VISCOSE', '', 'modal', 'modal', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'VISCOSE', '', 'liocel', 'liocel', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'VISCOSE', '', 'lyocell', 'lyocell', 'en'),
  ('VALUE', 'MATERIAL', 'POLYESTER', '', 'poliéster', 'poliester', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'POLYESTER', '', 'dri fit', 'dri fit', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'NYLON', '', 'poliamida', 'poliamida', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'NYLON', '', 'tactel', 'tactel', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'NYLON', '', 'polyamide', 'polyamide', 'en'),
  ('VALUE', 'MATERIAL', 'ACRYLIC', '', 'acrílico', 'acrilico', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FLEECE', '', 'moletom', 'moletom', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FLEECE', '', 'flanelado', 'flanelado', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FLEECE', '', 'soft', 'soft', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FLEECE', '', 'french terry', 'french terry', 'en'),
  ('VALUE', 'MATERIAL', 'KNIT', '', 'malha', 'malha', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'KNIT', '', 'tricô', 'trico', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'KNIT', '', 'tricot', 'tricot', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'KNIT', '', 'knitwear', 'knitwear', 'en'),
  ('VALUE', 'MATERIAL', 'CORDUROY', '', 'cotelê', 'cotele', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'CORDUROY', '', 'veludo cotelê', 'veludo cotele', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'VELVET', '', 'veludo', 'veludo', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'VELVET', '', 'plush', 'plush', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'CANVAS', '', 'lona', 'lona', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'MESH', '', 'tela', 'tela', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'MESH', '', 'arrastão', 'arrastao', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'LEATHER', '', 'couro', 'couro', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'LEATHER', '', 'couro legítimo', 'couro legitimo', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SUEDE', '', 'camurça', 'camurca', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SUEDE', '', 'nobuck', 'nobuck', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SUEDE', '', 'nubuck', 'nubuck', 'en'),
  ('VALUE', 'MATERIAL', 'FAUX_LEATHER', '', 'couro sintético', 'couro sintetico', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FAUX_LEATHER', '', 'couro ecológico', 'couro ecologico', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FAUX_LEATHER', '', 'corino', 'corino', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FAUX_LEATHER', '', 'pu', 'pu', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'FAUX_LEATHER', '', 'vegan leather', 'vegan leather', 'en'),
  ('VALUE', 'MATERIAL', 'SHEARLING', '', 'pelo', 'pelo', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SHEARLING', '', 'pelúcia', 'pelucia', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SHEARLING', '', 'teddy', 'teddy', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SHEARLING', '', 'pele sintética', 'pele sintetica', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SHEARLING', '', 'faux fur', 'faux fur', 'en'),
  ('VALUE', 'MATERIAL', 'RUBBER', '', 'borracha', 'borracha', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'CORK', '', 'cortiça', 'cortica', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'STRAW', '', 'palha', 'palha', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'STRAW', '', 'ráfia', 'rafia', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'STRAW', '', 'vime', 'vime', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'STRAW', '', 'raffia', 'raffia', 'en'),
  ('VALUE', 'MATERIAL', 'STRAW', '', 'wicker', 'wicker', 'en'),
  ('VALUE', 'MATERIAL', 'METAL', '', 'aço', 'aco', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'METAL', '', 'aço inox', 'aco inox', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'METAL', '', 'steel', 'steel', 'en'),
  ('VALUE', 'MATERIAL', 'METAL', '', 'stainless steel', 'stainless steel', 'en'),
  ('VALUE', 'MATERIAL', 'GOLD', '', 'ouro', 'ouro', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'GOLD', '', 'ouro 18k', 'ouro 18k', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SILVER', '', 'prata', 'prata', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SILVER', '', 'prata 925', 'prata 925', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SILVER', '', 'sterling silver', 'sterling silver', 'en'),
  ('VALUE', 'MATERIAL', 'PLATED', '', 'folheado', 'folheado', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'PLATED', '', 'semijoia', 'semijoia', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'PLATED', '', 'banhado', 'banhado', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'PLATED', '', 'gold plated', 'gold plated', 'en'),
  ('VALUE', 'MATERIAL', 'PEARL', '', 'pérola', 'perola', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'PEARL', '', 'pérolas', 'perolas', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'ACETATE', '', 'acetato', 'acetato', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'SYNTHETIC', '', 'sintético', 'sintetico', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'BLEND', '', 'misto', 'misto', 'pt-BR'),
  ('VALUE', 'MATERIAL', 'BLEND', '', 'mesclado', 'mesclado', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAIN', '', 'lisa', 'lisa', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAIN', '', 'liso', 'liso', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAIN', '', 'sem estampa', 'sem estampa', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAIN', '', 'solid', 'solid', 'en'),
  ('VALUE', 'PATTERN', 'STRIPES', '', 'listrada', 'listrada', 'pt-BR'),
  ('VALUE', 'PATTERN', 'STRIPES', '', 'listras', 'listras', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'PATTERN', 'STRIPES', '', 'risca de giz', 'risca de giz', 'pt-BR'),
  ('VALUE', 'PATTERN', 'STRIPES', '', 'striped', 'striped', 'en'),
  ('VALUE', 'PATTERN', 'STRIPES', '', 'pinstripe', 'pinstripe', 'en'),
  ('VALUE', 'PATTERN', 'PLAID', '', 'xadrez', 'xadrez', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAID', '', 'quadriculado', 'quadriculado', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAID', '', 'tartan', 'tartan', 'pt-BR'),
  ('VALUE', 'PATTERN', 'PLAID', '', 'check', 'check', 'en'),
  ('VALUE', 'PATTERN', 'GINGHAM', '', 'vichy', 'vichy', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GINGHAM', '', 'xadrez vichy', 'xadrez vichy', 'pt-BR'),
  ('VALUE', 'PATTERN', 'HOUNDSTOOTH', '', 'pied de poule', 'pied de poule', 'pt-BR'),
  ('VALUE', 'PATTERN', 'POLKA_DOT', '', 'poá', 'poa', 'pt-BR'),
  ('VALUE', 'PATTERN', 'POLKA_DOT', '', 'bolinhas', 'bolinhas', 'pt-BR'),
  ('VALUE', 'PATTERN', 'POLKA_DOT', '', 'dots', 'dots', 'en'),
  ('VALUE', 'PATTERN', 'GEOMETRIC', '', 'geométrica', 'geometrica', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GEOMETRIC', '', 'geométrico', 'geometrico', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ARGYLE', '', 'losangos', 'losangos', 'pt-BR'),
  ('VALUE', 'PATTERN', 'FLORAL', '', 'florida', 'florida', 'pt-BR'),
  ('VALUE', 'PATTERN', 'FLORAL', '', 'flores', 'flores', 'pt-BR'),
  ('VALUE', 'PATTERN', 'TROPICAL', '', 'folhagem', 'folhagem', 'pt-BR'),
  ('VALUE', 'PATTERN', 'TROPICAL', '', 'folhas', 'folhas', 'pt-BR'),
  ('VALUE', 'PATTERN', 'TROPICAL', '', 'palm', 'palm', 'en'),
  ('VALUE', 'PATTERN', 'PAISLEY', '', 'cashmere estampa', 'cashmere estampa', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ANIMAL_PRINT', '', 'oncinha', 'oncinha', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ANIMAL_PRINT', '', 'zebra', 'zebra', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ANIMAL_PRINT', '', 'cobra', 'cobra', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ANIMAL_PRINT', '', 'leopardo', 'leopardo', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ANIMAL_PRINT', '', 'leopard', 'leopard', 'en'),
  ('VALUE', 'PATTERN', 'ANIMAL_PRINT', '', 'snake', 'snake', 'en'),
  ('VALUE', 'PATTERN', 'CAMO', '', 'camuflada', 'camuflada', 'pt-BR'),
  ('VALUE', 'PATTERN', 'CAMO', '', 'camuflagem', 'camuflagem', 'pt-BR'),
  ('VALUE', 'PATTERN', 'CAMO', '', 'camouflage', 'camouflage', 'en'),
  ('VALUE', 'PATTERN', 'ABSTRACT', '', 'abstrata', 'abstrata', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ABSTRACT', '', 'abstrato', 'abstrato', 'pt-BR'),
  ('VALUE', 'PATTERN', 'COLOR_BLOCK', '', 'blocos de cor', 'blocos de cor', 'pt-BR'),
  ('VALUE', 'PATTERN', 'COLOR_BLOCK', '', 'bicolor', 'bicolor', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GRAPHIC', '', 'estampa', 'estampa', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GRAPHIC', '', 'estampada', 'estampada', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GRAPHIC', '', 'desenho', 'desenho', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GRAPHIC', '', 'arte', 'arte', 'pt-BR'),
  ('VALUE', 'PATTERN', 'GRAPHIC', '', 'print', 'print', 'en'),
  ('VALUE', 'PATTERN', 'GRAPHIC', '', 'artwork', 'artwork', 'en'),
  ('VALUE', 'PATTERN', 'ALLOVER_LOGO', '', 'monograma', 'monograma', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ALLOVER_LOGO', '', 'logo em toda', 'logo em toda', 'pt-BR'),
  ('VALUE', 'PATTERN', 'ALLOVER_LOGO', '', 'monogram', 'monogram', 'en'),
  ('VALUE', 'PATTERN', 'SINGLE_LOGO', '', 'logo', 'logo', 'pt-BR'),
  ('VALUE', 'PATTERN', 'SINGLE_LOGO', '', 'logo central', 'logo central', 'pt-BR'),
  ('VALUE', 'PATTERN', 'SINGLE_LOGO', '', 'logo no peito', 'logo no peito', 'pt-BR'),
  ('VALUE', 'PATTERN', 'SINGLE_LOGO', '', 'chest logo', 'chest logo', 'en'),
  ('VALUE', 'FINISH', 'RAW', '', 'jeans cru', 'jeans cru', 'pt-BR'),
  ('VALUE', 'FINISH', 'RAW', '', 'sem lavagem', 'sem lavagem', 'pt-BR'),
  ('VALUE', 'FINISH', 'RAW', '', 'dry', 'dry', 'pt-BR'),
  ('VALUE', 'FINISH', 'RAW', '', 'dry denim', 'dry denim', 'en'),
  ('VALUE', 'FINISH', 'RINSE', '', 'amaciado', 'amaciado', 'pt-BR'),
  ('VALUE', 'FINISH', 'RINSE', '', 'rinsed', 'rinsed', 'en'),
  ('VALUE', 'FINISH', 'DARK_WASH', '', 'lavagem escura', 'lavagem escura', 'pt-BR'),
  ('VALUE', 'FINISH', 'DARK_WASH', '', 'jeans escuro', 'jeans escuro', 'pt-BR'),
  ('VALUE', 'FINISH', 'DARK_WASH', '', 'denim escuro', 'denim escuro', 'pt-BR'),
  ('VALUE', 'FINISH', 'MEDIUM_WASH', '', 'lavagem média', 'lavagem media', 'pt-BR'),
  ('VALUE', 'FINISH', 'MEDIUM_WASH', '', 'jeans médio', 'jeans medio', 'pt-BR'),
  ('VALUE', 'FINISH', 'MEDIUM_WASH', '', 'denim médio', 'denim medio', 'pt-BR'),
  ('VALUE', 'FINISH', 'MEDIUM_WASH', '', 'mid wash', 'mid wash', 'en'),
  ('VALUE', 'FINISH', 'LIGHT_WASH', '', 'lavagem clara', 'lavagem clara', 'pt-BR'),
  ('VALUE', 'FINISH', 'LIGHT_WASH', '', 'jeans claro', 'jeans claro', 'pt-BR'),
  ('VALUE', 'FINISH', 'BLEACHED', '', 'delavê', 'delave', 'pt-BR'),
  ('VALUE', 'FINISH', 'BLEACHED', '', 'clareado', 'clareado', 'pt-BR'),
  ('VALUE', 'FINISH', 'BLEACHED', '', 'jeans clarinho', 'jeans clarinho', 'pt-BR'),
  ('VALUE', 'FINISH', 'BLEACHED', '', 'bleach wash', 'bleach wash', 'en'),
  ('VALUE', 'FINISH', 'STONE_WASH', '', 'stonado', 'stonado', 'pt-BR'),
  ('VALUE', 'FINISH', 'STONE_WASH', '', 'estonado', 'estonado', 'pt-BR'),
  ('VALUE', 'FINISH', 'STONE_WASH', '', 'stone', 'stone', 'pt-BR'),
  ('VALUE', 'FINISH', 'STONE_WASH', '', 'stonewashed', 'stonewashed', 'en'),
  ('VALUE', 'FINISH', 'ACID_WASH', '', 'marmorizado', 'marmorizado', 'pt-BR'),
  ('VALUE', 'FINISH', 'ACID_WASH', '', 'acid', 'acid', 'pt-BR'),
  ('VALUE', 'FINISH', 'FADED', '', 'desbotado', 'desbotado', 'pt-BR'),
  ('VALUE', 'FINISH', 'FADED', '', 'envelhecido', 'envelhecido', 'pt-BR'),
  ('VALUE', 'FINISH', 'FADED', '', 'used', 'used', 'pt-BR'),
  ('VALUE', 'FINISH', 'FADED', '', 'vintage wash', 'vintage wash', 'pt-BR'),
  ('VALUE', 'FINISH', 'FADED', '', 'washed', 'washed', 'en'),
  ('VALUE', 'FINISH', 'GARMENT_DYED', '', 'tingimento de peça', 'tingimento de peca', 'pt-BR'),
  ('VALUE', 'FINISH', 'GARMENT_DYED', '', 'tinturado', 'tinturado', 'pt-BR'),
  ('VALUE', 'FINISH', 'GARMENT_DYED', '', 'pigment dyed', 'pigment dyed', 'en'),
  ('VALUE', 'FINISH', 'RIPPED', '', 'destroyed', 'destroyed', 'pt-BR'),
  ('VALUE', 'FINISH', 'RIPPED', '', 'rasgado', 'rasgado', 'pt-BR'),
  ('VALUE', 'FINISH', 'RIPPED', '', 'rasgada', 'rasgada', 'pt-BR'),
  ('VALUE', 'FINISH', 'RIPPED', '', 'rasgos', 'rasgos', 'pt-BR'),
  ('VALUE', 'FINISH', 'DISTRESSED', '', 'puído', 'puido', 'pt-BR'),
  ('VALUE', 'FINISH', 'DISTRESSED', '', 'puida', 'puida', 'pt-BR'),
  ('VALUE', 'FINISH', 'DISTRESSED', '', 'desgastado', 'desgastado', 'pt-BR'),
  ('VALUE', 'FINISH', 'DISTRESSED', '', 'worn', 'worn', 'en'),
  ('VALUE', 'FINISH', 'FRAYED_HEM', '', 'barra desfiada', 'barra desfiada', 'pt-BR'),
  ('VALUE', 'FINISH', 'FRAYED_HEM', '', 'desfiado', 'desfiado', 'pt-BR'),
  ('VALUE', 'FINISH', 'FRAYED_HEM', '', 'barra a fio', 'barra a fio', 'pt-BR'),
  ('VALUE', 'FINISH', 'FRAYED_HEM', '', 'raw hem', 'raw hem', 'en'),
  ('VALUE', 'FINISH', 'REPAIRED', '', 'remendado', 'remendado', 'pt-BR'),
  ('VALUE', 'FINISH', 'REPAIRED', '', 'rip and repair', 'rip and repair', 'pt-BR'),
  ('VALUE', 'FINISH', 'COATED', '', 'resinado', 'resinado', 'pt-BR'),
  ('VALUE', 'FINISH', 'COATED', '', 'resinada', 'resinada', 'pt-BR'),
  ('VALUE', 'FINISH', 'COATED', '', 'waxed denim', 'waxed denim', 'en'),
  ('VALUE', 'FINISH', 'WAXED', '', 'encerado', 'encerado', 'pt-BR'),
  ('VALUE', 'FINISH', 'WAXED', '', 'encerada', 'encerada', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'FINISH', 'PATENT', '', 'verniz', 'verniz', 'pt-BR'),
  ('VALUE', 'FINISH', 'PATENT', '', 'envernizado', 'envernizado', 'pt-BR'),
  ('VALUE', 'FINISH', 'METALLIC', '', 'metalizado', 'metalizado', 'pt-BR'),
  ('VALUE', 'FINISH', 'METALLIC', '', 'laminado', 'laminado', 'pt-BR'),
  ('VALUE', 'FINISH', 'METALLIC', '', 'lamê', 'lame', 'pt-BR'),
  ('VALUE', 'FINISH', 'METALLIC', '', 'foil', 'foil', 'en'),
  ('VALUE', 'FINISH', 'SATIN_FINISH', '', 'acetinado', 'acetinado', 'pt-BR'),
  ('VALUE', 'FINISH', 'SATIN_FINISH', '', 'brilho acetinado', 'brilho acetinado', 'pt-BR'),
  ('VALUE', 'FINISH', 'SATIN_FINISH', '', 'sateen', 'sateen', 'en'),
  ('VALUE', 'FINISH', 'BRUSHED', '', 'peletizado', 'peletizado', 'pt-BR'),
  ('VALUE', 'FINISH', 'BRUSHED', '', 'escovado', 'escovado', 'pt-BR'),
  ('VALUE', 'FINISH', 'BRUSHED', '', 'peached', 'peached', 'pt-BR'),
  ('VALUE', 'FINISH', 'CABLE_KNIT', '', 'trançado', 'trancado', 'pt-BR'),
  ('VALUE', 'FINISH', 'CABLE_KNIT', '', 'tranças', 'trancas', 'pt-BR'),
  ('VALUE', 'FINISH', 'CABLE_KNIT', '', 'tricô trançado', 'trico trancado', 'pt-BR'),
  ('VALUE', 'FINISH', 'CABLE_KNIT', '', 'aran', 'aran', 'en'),
  ('VALUE', 'FINISH', 'RIBBED', '', 'canelado', 'canelado', 'pt-BR'),
  ('VALUE', 'FINISH', 'RIBBED', '', 'canelada', 'canelada', 'pt-BR'),
  ('VALUE', 'FINISH', 'RIBBED', '', 'ribana', 'ribana', 'pt-BR'),
  ('VALUE', 'FINISH', 'RIBBED', '', 'rib knit', 'rib knit', 'en'),
  ('VALUE', 'FINISH', 'WAFFLE', '', 'favo de mel', 'favo de mel', 'pt-BR'),
  ('VALUE', 'FINISH', 'WAFFLE', '', 'waffle knit', 'waffle knit', 'en'),
  ('VALUE', 'FINISH', 'CHUNKY_KNIT', '', 'tricô grosso', 'trico grosso', 'pt-BR'),
  ('VALUE', 'FINISH', 'CHUNKY_KNIT', '', 'tricot grosso', 'tricot grosso', 'pt-BR'),
  ('VALUE', 'FINISH', 'POINTELLE', '', 'furadinho', 'furadinho', 'pt-BR'),
  ('VALUE', 'FINISH', 'CROCHET', '', 'crochê', 'croche', 'pt-BR'),
  ('VALUE', 'FINISH', 'EMBROIDERED', '', 'bordado', 'bordado', 'pt-BR'),
  ('VALUE', 'FINISH', 'EMBROIDERED', '', 'bordada', 'bordada', 'pt-BR'),
  ('VALUE', 'FINISH', 'EMBROIDERED', '', 'bordados', 'bordados', 'pt-BR'),
  ('VALUE', 'FINISH', 'EMBROIDERED', '', 'embroidery', 'embroidery', 'en'),
  ('VALUE', 'FINISH', 'SEQUINED', '', 'paetê', 'paete', 'pt-BR'),
  ('VALUE', 'FINISH', 'SEQUINED', '', 'lantejoula', 'lantejoula', 'pt-BR'),
  ('VALUE', 'FINISH', 'SEQUINED', '', 'sequin', 'sequin', 'en'),
  ('VALUE', 'FINISH', 'BEADED', '', 'pedraria', 'pedraria', 'pt-BR'),
  ('VALUE', 'FINISH', 'BEADED', '', 'miçangas', 'micangas', 'pt-BR'),
  ('VALUE', 'FINISH', 'BEADED', '', 'bordado de pedras', 'bordado de pedras', 'pt-BR'),
  ('VALUE', 'FINISH', 'BEADED', '', 'embellished', 'embellished', 'en'),
  ('VALUE', 'FINISH', 'STUDDED', '', 'tachas', 'tachas', 'pt-BR'),
  ('VALUE', 'FINISH', 'STUDDED', '', 'spikes', 'spikes', 'pt-BR'),
  ('VALUE', 'FINISH', 'STUDDED', '', 'taxas', 'taxas', 'pt-BR'),
  ('VALUE', 'FINISH', 'STUDDED', '', 'spiked', 'spiked', 'en'),
  ('VALUE', 'FINISH', 'FRINGED', '', 'franja', 'franja', 'pt-BR'),
  ('VALUE', 'FINISH', 'FRINGED', '', 'franjas', 'franjas', 'pt-BR'),
  ('VALUE', 'FINISH', 'FRINGED', '', 'fringe', 'fringe', 'en'),
  ('VALUE', 'FINISH', 'RUFFLED', '', 'babado', 'babado', 'pt-BR'),
  ('VALUE', 'FINISH', 'RUFFLED', '', 'babados', 'babados', 'pt-BR'),
  ('VALUE', 'FINISH', 'RUFFLED', '', 'ruffle', 'ruffle', 'en'),
  ('VALUE', 'FINISH', 'RUFFLED', '', 'frill', 'frill', 'en'),
  ('VALUE', 'LENGTH', 'CROPPED', '', 'curta', 'curta', 'pt-BR'),
  ('VALUE', 'LENGTH', 'CROPPED', '', 'curtinha', 'curtinha', 'pt-BR'),
  ('VALUE', 'LENGTH', 'CROPPED', '', 'crop', 'crop', 'en'),
  ('VALUE', 'LENGTH', 'REGULAR_LENGTH', '', 'comprimento regular', 'comprimento regular', 'pt-BR'),
  ('VALUE', 'LENGTH', 'REGULAR_LENGTH', '', 'no quadril', 'no quadril', 'pt-BR'),
  ('VALUE', 'LENGTH', 'REGULAR_LENGTH', '', 'hip length', 'hip length', 'en'),
  ('VALUE', 'LENGTH', 'LONGLINE', '', 'alongado', 'alongado', 'pt-BR'),
  ('VALUE', 'LENGTH', 'LONGLINE', '', 'alongada', 'alongada', 'pt-BR'),
  ('VALUE', 'LENGTH', 'LONGLINE', '', 'túnica', 'tunica', 'pt-BR'),
  ('VALUE', 'LENGTH', 'LONGLINE', '', 'tunic length', 'tunic length', 'en'),
  ('VALUE', 'LENGTH', 'MICRO', '', 'hot pants', 'hot pants', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MICRO', '', 'curtíssimo', 'curtissimo', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MINI', '', 'curto', 'curto', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MINI', '', 'short', 'short', 'en'),
  ('VALUE', 'LENGTH', 'MID_THIGH', '', 'meio da coxa', 'meio da coxa', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MID_THIGH', '', 'médio', 'medio', 'pt-BR'),
  ('VALUE', 'LENGTH', 'KNEE', '', 'joelho', 'joelho', 'pt-BR'),
  ('VALUE', 'LENGTH', 'KNEE', '', 'bermuda', 'bermuda', 'pt-BR'),
  ('VALUE', 'LENGTH', 'KNEE', '', 'na altura do joelho', 'na altura do joelho', 'pt-BR'),
  ('VALUE', 'LENGTH', 'KNEE', '', 'knee length', 'knee length', 'en'),
  ('VALUE', 'LENGTH', 'MIDI', '', 'longuete', 'longuete', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MIDI', '', 'abaixo do joelho', 'abaixo do joelho', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MIDI', '', 'below the knee', 'below the knee', 'en'),
  ('VALUE', 'LENGTH', 'MAXI', '', 'longo', 'longo', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MAXI', '', 'vestido longo', 'vestido longo', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MAXI', '', 'saia longa', 'saia longa', 'pt-BR'),
  ('VALUE', 'LENGTH', 'MAXI', '', 'long', 'long', 'en'),
  ('VALUE', 'LENGTH', 'MAXI', '', 'maxi length', 'maxi length', 'en'),
  ('VALUE', 'LENGTH', 'FLOOR_LENGTH', '', 'até o chão', 'ate o chao', 'pt-BR'),
  ('VALUE', 'LENGTH', 'FLOOR_LENGTH', '', 'longuíssimo', 'longuissimo', 'pt-BR'),
  ('VALUE', 'LENGTH', 'FLOOR_LENGTH', '', 'gown length', 'gown length', 'en'),
  ('VALUE', 'LENGTH', 'FULL_LENGTH', '', 'calça longa', 'calca longa', 'pt-BR'),
  ('VALUE', 'LENGTH', 'FULL_LENGTH', '', 'comprimento total', 'comprimento total', 'pt-BR'),
  ('VALUE', 'LENGTH', 'ANKLE_LENGTH', '', '7/8', '7 8', 'pt-BR'),
  ('VALUE', 'LENGTH', 'ANKLE_LENGTH', '', 'cropped', 'cropped', 'pt-BR'),
  ('VALUE', 'LENGTH', 'ANKLE_LENGTH', '', 'tornozelo', 'tornozelo', 'pt-BR'),
  ('VALUE', 'LENGTH', 'ANKLE_LENGTH', '', 'calça cropped', 'calca cropped', 'pt-BR'),
  ('VALUE', 'LENGTH', 'CAPRI', '', 'meia canela', 'meia canela', 'pt-BR'),
  ('VALUE', 'LENGTH', 'CAPRI', '', 'pantacourt', 'pantacourt', 'pt-BR'),
  ('VALUE', 'LENGTH', 'CAPRI', '', 'mid calf', 'mid calf', 'en'),
  ('VALUE', 'LENGTH', 'PEDAL_PUSHER', '', 'corsário', 'corsario', 'pt-BR'),
  ('VALUE', 'LENGTH', 'PEDAL_PUSHER', '', 'pescador', 'pescador', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'LOW_TOP', '', 'cano baixo', 'cano baixo', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'LOW_TOP', '', 'low', 'low', 'en'),
  ('VALUE', 'SHAFT_HEIGHT', 'MID_TOP', '', 'tênis cano médio', 'tenis cano medio', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'MID_TOP', '', 'mid', 'mid', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'HIGH_TOP', '', 'cano alto', 'cano alto', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'HIGH_TOP', '', 'tênis cano alto', 'tenis cano alto', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'HIGH_TOP', '', 'hi', 'hi', 'en'),
  ('VALUE', 'SHAFT_HEIGHT', 'NO_SHOW', '', 'invisível', 'invisivel', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'NO_SHOW', '', 'sapatilha', 'sapatilha', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'NO_SHOW', '', 'meia sapatilha', 'meia sapatilha', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'SHAFT_HEIGHT', 'NO_SHOW', '', 'liner', 'liner', 'en'),
  ('VALUE', 'SHAFT_HEIGHT', 'ANKLE', '', 'cano curto', 'cano curto', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'ANKLE', '', 'bota curta', 'bota curta', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'ANKLE', '', 'botinha', 'botinha', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'ANKLE', '', 'soquete', 'soquete', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'ANKLE', '', 'ankle boot', 'ankle boot', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'QUARTER', '', 'meia cano curto', 'meia cano curto', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'CREW', '', 'meia cano médio', 'meia cano medio', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'MID_CALF', '', 'bota cano médio', 'bota cano medio', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'MID_CALF', '', 'meia canela', 'meia canela', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'KNEE_HIGH', '', 'cano longo', 'cano longo', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'KNEE_HIGH', '', 'bota cano longo', 'bota cano longo', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'KNEE_HIGH', '', 'bota alta', 'bota alta', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'KNEE_HIGH', '', 'meia 3/4', 'meia 3 4', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'KNEE_HIGH', '', 'tall boot', 'tall boot', 'en'),
  ('VALUE', 'SHAFT_HEIGHT', 'OVER_THE_KNEE', '', 'acima do joelho', 'acima do joelho', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'OVER_THE_KNEE', '', 'meia 7/8', 'meia 7 8', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'OVER_THE_KNEE', '', 'OTK', 'otk', 'en'),
  ('VALUE', 'SHAFT_HEIGHT', 'THIGH_HIGH', '', 'bota coxa', 'bota coxa', 'pt-BR'),
  ('VALUE', 'SHAFT_HEIGHT', 'THIGH_HIGH', '', 'meia de coxa', 'meia de coxa', 'pt-BR'),
  ('VALUE', 'RISE', 'LOW_RISE', '', 'cintura baixa', 'cintura baixa', 'pt-BR'),
  ('VALUE', 'RISE', 'LOW_RISE', '', 'cós baixo', 'cos baixo', 'pt-BR'),
  ('VALUE', 'RISE', 'LOW_RISE', '', 'saint tropez', 'saint tropez', 'pt-BR'),
  ('VALUE', 'RISE', 'LOW_RISE', '', 'low waist', 'low waist', 'en'),
  ('VALUE', 'RISE', 'MID_RISE', '', 'cintura média', 'cintura media', 'pt-BR'),
  ('VALUE', 'RISE', 'MID_RISE', '', 'cintura normal', 'cintura normal', 'pt-BR'),
  ('VALUE', 'RISE', 'MID_RISE', '', 'regular rise', 'regular rise', 'en'),
  ('VALUE', 'RISE', 'HIGH_RISE', '', 'cintura alta', 'cintura alta', 'pt-BR'),
  ('VALUE', 'RISE', 'HIGH_RISE', '', 'cós alto', 'cos alto', 'pt-BR'),
  ('VALUE', 'RISE', 'HIGH_RISE', '', 'high waist', 'high waist', 'en'),
  ('VALUE', 'RISE', 'SUPER_HIGH_RISE', '', 'cintura altíssima', 'cintura altissima', 'pt-BR'),
  ('VALUE', 'RISE', 'SUPER_HIGH_RISE', '', 'super alta', 'super alta', 'pt-BR'),
  ('VALUE', 'RISE', 'SUPER_HIGH_RISE', '', 'ultra high rise', 'ultra high rise', 'en'),
  ('VALUE', 'RISE', 'SUPER_HIGH_RISE', '', 'ribcage', 'ribcage', 'en'),
  ('VALUE', 'HEM', 'ASYMMETRIC', '', 'assimétrica', 'assimetrica', 'pt-BR'),
  ('VALUE', 'HEM', 'ASYMMETRIC', '', 'assimétrico', 'assimetrico', 'pt-BR'),
  ('VALUE', 'HEM', 'ASYMMETRIC', '', 'barra assimétrica', 'barra assimetrica', 'pt-BR'),
  ('VALUE', 'HEM', 'ASYMMETRIC', '', 'asymmetrical', 'asymmetrical', 'en'),
  ('VALUE', 'HEM', 'HIGH_LOW', '', 'mullet', 'mullet', 'pt-BR'),
  ('VALUE', 'HEM', 'HIGH_LOW', '', 'mais longo atrás', 'mais longo atras', 'pt-BR'),
  ('VALUE', 'HEM', 'HIGH_LOW', '', 'mullet hem', 'mullet hem', 'en'),
  ('VALUE', 'HEM', 'HANDKERCHIEF', '', 'pontas', 'pontas', 'pt-BR'),
  ('VALUE', 'HEM', 'HANDKERCHIEF', '', 'barra de pontas', 'barra de pontas', 'pt-BR'),
  ('VALUE', 'HEM', 'HANDKERCHIEF', '', 'lenço', 'lenco', 'pt-BR'),
  ('VALUE', 'HEM', 'HANDKERCHIEF', '', 'handkerchief hem', 'handkerchief hem', 'en'),
  ('VALUE', 'HEM', 'SLIT', '', 'fenda', 'fenda', 'pt-BR'),
  ('VALUE', 'HEM', 'SLIT', '', 'com fenda', 'com fenda', 'pt-BR'),
  ('VALUE', 'HEM', 'SLIT', '', 'split', 'split', 'en'),
  ('VALUE', 'SLEEVE_LENGTH', 'SLEEVELESS', '', 'sem manga', 'sem manga', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'SLEEVELESS', '', 'regata', 'regata', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'SHORT_SLEEVE', '', 'manga curta', 'manga curta', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'ELBOW_SLEEVE', '', 'meia manga', 'meia manga', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'ELBOW_SLEEVE', '', 'até o cotovelo', 'ate o cotovelo', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'THREE_QUARTER_SLEEVE', '', 'manga 3/4', 'manga 3 4', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'THREE_QUARTER_SLEEVE', '', 'três quartos', 'tres quartos', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'THREE_QUARTER_SLEEVE', '', '3/4 sleeve', '3 4 sleeve', 'en'),
  ('VALUE', 'SLEEVE_LENGTH', 'LONG_SLEEVE', '', 'manga longa', 'manga longa', 'pt-BR'),
  ('VALUE', 'SLEEVE_LENGTH', 'LONG_SLEEVE', '', 'manga comprida', 'manga comprida', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'SET_IN', '', 'manga comum', 'manga comum', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'SET_IN', '', 'manga tradicional', 'manga tradicional', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'DROP_SHOULDER', '', 'ombro caído', 'ombro caido', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'DROP_SHOULDER', '', 'ombro deslocado', 'ombro deslocado', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'DROP_SHOULDER', '', 'dropped shoulder', 'dropped shoulder', 'en'),
  ('VALUE', 'SLEEVE_STYLE', 'DOLMAN', '', 'morcego', 'morcego', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'DOLMAN', '', 'manga morcego', 'manga morcego', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'DOLMAN', '', 'batwing', 'batwing', 'en'),
  ('VALUE', 'SLEEVE_STYLE', 'KIMONO_SLEEVE', '', 'manga japonesa', 'manga japonesa', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'KIMONO_SLEEVE', '', 'quimono', 'quimono', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'PUFF', '', 'bufante', 'bufante', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'PUFF', '', 'manga bufante', 'manga bufante', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'PUFF', '', 'princesa', 'princesa', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'PUFF', '', 'puff sleeve', 'puff sleeve', 'en'),
  ('VALUE', 'SLEEVE_STYLE', 'BALLOON_SLEEVE', '', 'manga balão', 'manga balao', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'BALLOON_SLEEVE', '', 'bispo', 'bispo', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'BALLOON_SLEEVE', '', 'bishop sleeve', 'bishop sleeve', 'en'),
  ('VALUE', 'SLEEVE_STYLE', 'BELL', '', 'manga sino', 'manga sino', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'BELL', '', 'bell sleeve', 'bell sleeve', 'en'),
  ('VALUE', 'SLEEVE_STYLE', 'FLUTTER', '', 'manga de babado', 'manga de babado', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'FLUTTER', '', 'manguinha babado', 'manguinha babado', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'FLUTTER', '', 'flutter sleeve', 'flutter sleeve', 'en'),
  ('VALUE', 'SLEEVE_STYLE', 'CAP_SLEEVE', '', 'manguinha', 'manguinha', 'pt-BR'),
  ('VALUE', 'SLEEVE_STYLE', 'CAP_SLEEVE', '', 'cap', 'cap', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'CREW', '', 'careca', 'careca', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'CREW', '', 'gola redonda', 'gola redonda', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'CREW', '', 'redonda', 'redonda', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'CREW', '', 'crew neck', 'crew neck', 'en'),
  ('VALUE', 'NECKLINE', 'CREW', '', 'round neck', 'round neck', 'en'),
  ('VALUE', 'NECKLINE', 'V_NECK', '', 'decote v', 'decote v', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'V_NECK', '', 'gola v', 'gola v', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SCOOP', '', 'decote u', 'decote u', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SCOOP', '', 'canoa aberta', 'canoa aberta', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SCOOP', '', 'u neck', 'u neck', 'en'),
  ('VALUE', 'NECKLINE', 'BOAT', '', 'canoa', 'canoa', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'BOAT', '', 'gola canoa', 'gola canoa', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'BOAT', '', 'boat neck', 'boat neck', 'en'),
  ('VALUE', 'NECKLINE', 'BOAT', '', 'bateau', 'bateau', 'en'),
  ('VALUE', 'NECKLINE', 'SQUARE_NECK', '', 'decote quadrado', 'decote quadrado', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SWEETHEART', '', 'coração', 'coracao', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SWEETHEART', '', 'decote coração', 'decote coracao', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'PLUNGE', '', 'decote profundo', 'decote profundo', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'NECKLINE', 'PLUNGE', '', 'decotão', 'decotao', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'PLUNGE', '', 'deep v', 'deep v', 'en'),
  ('VALUE', 'NECKLINE', 'OFF_SHOULDER', '', 'ombro a ombro', 'ombro a ombro', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'OFF_SHOULDER', '', 'ciganinha', 'ciganinha', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'OFF_SHOULDER', '', 'ombros de fora', 'ombros de fora', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'OFF_SHOULDER', '', 'bardot', 'bardot', 'en'),
  ('VALUE', 'NECKLINE', 'ONE_SHOULDER', '', 'um ombro só', 'um ombro so', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'ONE_SHOULDER', '', 'ombro só', 'ombro so', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'ONE_SHOULDER', '', 'assimétrico', 'assimetrico', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'HALTER', '', 'frente única', 'frente unica', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'HALTER', '', 'halterneck', 'halterneck', 'en'),
  ('VALUE', 'NECKLINE', 'STRAPLESS', '', 'tomara que caia', 'tomara que caia', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'STRAPLESS', '', 'sem alça', 'sem alca', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'COWL', '', 'decote drapeado', 'decote drapeado', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'COWL', '', 'degagê', 'degage', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'COWL', '', 'cowl neck', 'cowl neck', 'en'),
  ('VALUE', 'NECKLINE', 'KEYHOLE', '', 'decote gota', 'decote gota', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'TURTLENECK', '', 'gola alta', 'gola alta', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'TURTLENECK', '', 'gola rolê', 'gola role', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'TURTLENECK', '', 'rolê', 'role', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'TURTLENECK', '', 'roll neck', 'roll neck', 'en'),
  ('VALUE', 'NECKLINE', 'MOCK_NECK', '', 'gola média', 'gola media', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'MOCK_NECK', '', 'meia gola alta', 'meia gola alta', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'MOCK_NECK', '', 'funnel neck', 'funnel neck', 'en'),
  ('VALUE', 'NECKLINE', 'HENLEY', '', 'portinhola', 'portinhola', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'POLO_COLLAR', '', 'gola polo', 'gola polo', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHIRT_COLLAR', '', 'colarinho', 'colarinho', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHIRT_COLLAR', '', 'gola de camisa', 'gola de camisa', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHIRT_COLLAR', '', 'gola italiana', 'gola italiana', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHIRT_COLLAR', '', 'point collar', 'point collar', 'en'),
  ('VALUE', 'NECKLINE', 'SHIRT_COLLAR', '', 'spread collar', 'spread collar', 'en'),
  ('VALUE', 'NECKLINE', 'BUTTON_DOWN_COLLAR', '', 'button down', 'button down', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'BUTTON_DOWN_COLLAR', '', 'pontas abotoadas', 'pontas abotoadas', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'MANDARIN', '', 'gola padre', 'gola padre', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'MANDARIN', '', 'mandarim', 'mandarim', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'MANDARIN', '', 'gola de padre', 'gola de padre', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'MANDARIN', '', 'band collar', 'band collar', 'en'),
  ('VALUE', 'NECKLINE', 'CAMP_COLLAR', '', 'gola cubana', 'gola cubana', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'CAMP_COLLAR', '', 'camisa cubana', 'camisa cubana', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'CAMP_COLLAR', '', 'cuban collar', 'cuban collar', 'en'),
  ('VALUE', 'NECKLINE', 'PETER_PAN', '', 'gola boneca', 'gola boneca', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'PETER_PAN', '', 'peter pan collar', 'peter pan collar', 'en'),
  ('VALUE', 'NECKLINE', 'BOW_COLLAR', '', 'gola laço', 'gola laco', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'BOW_COLLAR', '', 'gola com laço', 'gola com laco', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'BOW_COLLAR', '', 'pussy bow', 'pussy bow', 'en'),
  ('VALUE', 'NECKLINE', 'HOOD', '', 'capuz', 'capuz', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'HOOD', '', 'com capuz', 'com capuz', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'HOOD', '', 'hooded', 'hooded', 'en'),
  ('VALUE', 'NECKLINE', 'NOTCH_LAPEL', '', 'lapela', 'lapela', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'NOTCH_LAPEL', '', 'lapela tradicional', 'lapela tradicional', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'PEAK_LAPEL', '', 'lapela pontiaguda', 'lapela pontiaguda', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'PEAK_LAPEL', '', 'lapela bico', 'lapela bico', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHAWL_LAPEL', '', 'gola xale', 'gola xale', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHAWL_LAPEL', '', 'lapela xale', 'lapela xale', 'pt-BR'),
  ('VALUE', 'NECKLINE', 'SHAWL_LAPEL', '', 'shawl collar', 'shawl collar', 'en'),
  ('VALUE', 'CLOSURE', 'PULLOVER', '', 'sem fechamento', 'sem fechamento', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'PULLOVER', '', 'fechado', 'fechado', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'PULLOVER', '', 'canguru', 'canguru', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'PULLOVER', '', 'vestir pela cabeça', 'vestir pela cabeca', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'BUTTON', '', 'botão', 'botao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'BUTTON', '', 'botões', 'botoes', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'BUTTON', '', 'abotoado', 'abotoado', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'BUTTON', '', 'buttoned', 'buttoned', 'en'),
  ('VALUE', 'CLOSURE', 'SNAP', '', 'pressão', 'pressao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'SNAP', '', 'botão de pressão', 'botao de pressao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'SNAP', '', 'press stud', 'press stud', 'en'),
  ('VALUE', 'CLOSURE', 'ZIPPER', '', 'zíper', 'ziper', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'ZIPPER', '', 'com zíper', 'com ziper', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'ZIPPER', '', 'aberto', 'aberto', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'ZIPPER', '', 'zip', 'zip', 'en'),
  ('VALUE', 'CLOSURE', 'ZIPPER', '', 'full zip', 'full zip', 'en'),
  ('VALUE', 'CLOSURE', 'HALF_ZIP', '', 'meio zíper', 'meio ziper', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'HALF_ZIP', '', '1/4 zip', '1 4 zip', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'HALF_ZIP', '', 'quarter zip', 'quarter zip', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'SINGLE_BREASTED', '', 'abotoamento simples', 'abotoamento simples', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'SINGLE_BREASTED', '', 'uma carreira', 'uma carreira', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'DOUBLE_BREASTED', '', 'transpassado', 'transpassado', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'DOUBLE_BREASTED', '', 'duas carreiras', 'duas carreiras', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'DOUBLE_BREASTED', '', 'jaquetão', 'jaquetao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'HOOK_AND_EYE', '', 'colchete', 'colchete', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'TIE', '', 'amarração', 'amarracao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'TIE', '', 'amarrar', 'amarrar', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'TIE', '', 'faixa', 'faixa', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'TIE', '', 'tie fastening', 'tie fastening', 'en'),
  ('VALUE', 'CLOSURE', 'DRAWSTRING', '', 'cordão', 'cordao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'DRAWSTRING', '', 'cordinha', 'cordinha', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'ELASTIC', '', 'elástico', 'elastico', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'ELASTIC', '', 'cós elástico', 'cos elastico', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'LACE_UP', '', 'cadarço', 'cadarco', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'LACE_UP', '', 'de amarrar', 'de amarrar', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'LACE_UP', '', 'laces', 'laces', 'en'),
  ('VALUE', 'CLOSURE', 'SLIP_ON', '', 'sem cadarço', 'sem cadarco', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'SLIP_ON', '', 'calce fácil', 'calce facil', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'SLIP_ON', '', 'laceless', 'laceless', 'en'),
  ('VALUE', 'CLOSURE', 'VELCRO', '', 'hook and loop', 'hook and loop', 'en'),
  ('VALUE', 'CLOSURE', 'BUCKLE', '', 'fivela', 'fivela', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'MAGNETIC', '', 'ímã', 'ima', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'MAGNETIC', '', 'magnético', 'magnetico', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'TOGGLE', '', 'pino', 'pino', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'TOGGLE', '', 'alamar', 'alamar', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'CLOSURE', 'FLAP', '', 'aba', 'aba', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'FLAP', '', 'com aba', 'com aba', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'OPEN_TOP', '', 'aberta', 'aberta', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'OPEN_TOP', '', 'sem fecho', 'sem fecho', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'CLASP', '', 'fecho', 'fecho', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'CLASP', '', 'fecho lagosta', 'fecho lagosta', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'CLASP', '', 'fecho de joia', 'fecho de joia', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'CLASP', '', 'lobster clasp', 'lobster clasp', 'en'),
  ('VALUE', 'CLOSURE', 'CLIP_ON', '', 'brinco de pressão', 'brinco de pressao', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'CLIP_ON', '', 'sem furo', 'sem furo', 'pt-BR'),
  ('VALUE', 'CLOSURE', 'CLIP_ON', '', 'clip', 'clip', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'STILETTO', '', 'agulha', 'agulha', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'STILETTO', '', 'salto agulha', 'salto agulha', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'STILETTO', '', 'salto fino', 'salto fino', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'BLOCK', '', 'bloco', 'bloco', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'BLOCK', '', 'salto grosso', 'salto grosso', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'BLOCK', '', 'salto quadrado', 'salto quadrado', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'BLOCK', '', 'chunky heel', 'chunky heel', 'en'),
  ('VALUE', 'HEEL_TYPE', 'KITTEN', '', 'gatinho', 'gatinho', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'KITTEN', '', 'salto baixinho fino', 'salto baixinho fino', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'KITTEN', '', 'kitten heel', 'kitten heel', 'en'),
  ('VALUE', 'HEEL_TYPE', 'WEDGE', '', 'anabela', 'anabela', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'WEDGE', '', 'plataforma anabela', 'plataforma anabela', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'CONE', '', 'salto cone', 'salto cone', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'CONE', '', 'cone heel', 'cone heel', 'en'),
  ('VALUE', 'HEEL_TYPE', 'SPOOL', '', 'carretel', 'carretel', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'SPOOL', '', 'spool heel', 'spool heel', 'en'),
  ('VALUE', 'HEEL_TYPE', 'CUBAN', '', 'cubano', 'cubano', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'CUBAN', '', 'salto cubano', 'salto cubano', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'CUBAN', '', 'cuban heel', 'cuban heel', 'en'),
  ('VALUE', 'HEEL_TYPE', 'SCULPTURAL', '', 'geométrico', 'geometrico', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'SCULPTURAL', '', 'escultural', 'escultural', 'pt-BR'),
  ('VALUE', 'HEEL_TYPE', 'SCULPTURAL', '', 'sculptural heel', 'sculptural heel', 'en'),
  ('VALUE', 'HEEL_HEIGHT', 'FLAT', '', 'rasteiro', 'rasteiro', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'FLAT', '', 'rasteira', 'rasteira', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'FLAT', '', 'sem salto', 'sem salto', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'FLAT', '', 'baixo', 'baixo', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'LOW', '', 'salto baixo', 'salto baixo', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'LOW', '', 'low heel', 'low heel', 'en'),
  ('VALUE', 'HEEL_HEIGHT', 'MID', '', 'salto médio', 'salto medio', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'MID', '', 'mid heel', 'mid heel', 'en'),
  ('VALUE', 'HEEL_HEIGHT', 'HIGH', '', 'salto alto', 'salto alto', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'HIGH', '', 'high heel', 'high heel', 'en'),
  ('VALUE', 'HEEL_HEIGHT', 'VERY_HIGH', '', 'altíssimo', 'altissimo', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'VERY_HIGH', '', 'meia pata alta', 'meia pata alta', 'pt-BR'),
  ('VALUE', 'HEEL_HEIGHT', 'VERY_HIGH', '', 'very high heel', 'very high heel', 'en'),
  ('VALUE', 'TOE_SHAPE', 'ROUND_TOE', '', 'bico redondo', 'bico redondo', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'ALMOND_TOE', '', 'bico amendoado', 'bico amendoado', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'POINTED_TOE', '', 'bico fino', 'bico fino', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'POINTED_TOE', '', 'bico pontudo', 'bico pontudo', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'SQUARE_TOE', '', 'bico quadrado', 'bico quadrado', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'PEEP_TOE', '', 'dedinho de fora', 'dedinho de fora', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'OPEN_TOE', '', 'bico aberto', 'bico aberto', 'pt-BR'),
  ('VALUE', 'TOE_SHAPE', 'OPEN_TOE', '', 'dedos de fora', 'dedos de fora', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'PLATFORM', '', 'plataforma', 'plataforma', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'FRONT_PLATFORM', '', 'meia pata', 'meia pata', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'FLATFORM', '', 'plataforma reta', 'plataforma reta', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'LUG', '', 'tratorado', 'tratorado', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'LUG', '', 'tratorada', 'tratorada', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'LUG', '', 'sola tratorada', 'sola tratorada', 'pt-BR'),
  ('VALUE', 'SOLE_TYPE', 'LUG', '', 'lug sole', 'lug sole', 'en'),
  ('VALUE', 'SOLE_TYPE', 'LUG', '', 'track sole', 'track sole', 'en'),
  ('VALUE', 'SOLE_TYPE', 'LUG', '', 'chunky sole', 'chunky sole', 'en'),
  ('VALUE', 'SPORT_USE', 'LIFESTYLE', '', 'casual', 'casual', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'LIFESTYLE', '', 'dia a dia', 'dia a dia', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'RUNNING', '', 'corrida', 'corrida', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TRAINING', '', 'academia', 'academia', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TRAINING', '', 'treino', 'treino', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TRAINING', '', 'funcional', 'funcional', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TRAINING', '', 'crossfit', 'crossfit', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TRAINING', '', 'gym', 'gym', 'en'),
  ('VALUE', 'SPORT_USE', 'BASKETBALL', '', 'basquete', 'basquete', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'SKATE', '', 'skateboarding', 'skateboarding', 'en'),
  ('VALUE', 'SPORT_USE', 'FOOTBALL', '', 'futebol', 'futebol', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'FOOTBALL', '', 'chuteira', 'chuteira', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'FOOTBALL', '', 'society', 'society', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'FOOTBALL', '', 'futsal', 'futsal', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'FOOTBALL', '', 'soccer', 'soccer', 'en'),
  ('VALUE', 'SPORT_USE', 'TENNIS', '', 'tênis', 'tenis', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TENNIS', '', 'padel', 'padel', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'TENNIS', '', 'beach tennis', 'beach tennis', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'VOLLEYBALL', '', 'vôlei', 'volei', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'CYCLING', '', 'ciclismo', 'ciclismo', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'CYCLING', '', 'bike', 'bike', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'SWIM_SURF', '', 'natação', 'natacao', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'SWIM_SURF', '', 'surf', 'surf', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'SWIM_SURF', '', 'praia', 'praia', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'SWIM_SURF', '', 'swim', 'swim', 'en'),
  ('VALUE', 'SPORT_USE', 'HIKING', '', 'trilha', 'trilha', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'HIKING', '', 'trekking', 'trekking', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'HIKING', '', 'outdoor', 'outdoor', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'HIKING', '', 'montanha', 'montanha', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'HIKING', '', 'trail', 'trail', 'en'),
  ('VALUE', 'SPORT_USE', 'YOGA_PILATES', '', 'yoga', 'yoga', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'YOGA_PILATES', '', 'ioga', 'ioga', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'YOGA_PILATES', '', 'pilates', 'pilates', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'DANCE', '', 'dança', 'danca', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'DANCE', '', 'balé', 'bale', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'COMBAT_SPORTS', '', 'luta', 'luta', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'COMBAT_SPORTS', '', 'lutas', 'lutas', 'pt-BR');
INSERT INTO taxonomy_aliases (target_type, dimension_code, target_code, scope_subcategory_code, alias, alias_norm, locale) VALUES
  ('VALUE', 'SPORT_USE', 'COMBAT_SPORTS', '', 'boxe', 'boxe', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'COMBAT_SPORTS', '', 'jiu jitsu', 'jiu jitsu', 'pt-BR'),
  ('VALUE', 'SPORT_USE', 'COMBAT_SPORTS', '', 'boxing', 'boxing', 'en'),
  ('VALUE', 'SPORT_USE', 'GOLF', '', 'golfe', 'golfe', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'HAND', '', 'de mão', 'de mao', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'HAND', '', 'na mão', 'na mao', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'HAND', '', 'handheld', 'handheld', 'en'),
  ('VALUE', 'CARRY_MODE', 'SHOULDER', '', 'de ombro', 'de ombro', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'SHOULDER', '', 'no ombro', 'no ombro', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'CROSSBODY', '', 'transversal', 'transversal', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'CROSSBODY', '', 'tiracolo', 'tiracolo', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'CROSSBODY', '', 'atravessada', 'atravessada', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'WAIST', '', 'na cintura', 'na cintura', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'WAIST', '', 'belt', 'belt', 'en'),
  ('VALUE', 'CARRY_MODE', 'BACK', '', 'nas costas', 'nas costas', 'pt-BR'),
  ('VALUE', 'CARRY_MODE', 'BACK', '', 'backpack style', 'backpack style', 'en'),
  ('VALUE', 'CARRY_MODE', 'WRIST', '', 'de pulso', 'de pulso', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'FULL_RIM', '', 'aro fechado', 'aro fechado', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'FULL_RIM', '', 'aro inteiro', 'aro inteiro', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'SEMI_RIMLESS', '', 'fio de nylon', 'fio de nylon', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'SEMI_RIMLESS', '', 'meio aro', 'meio aro', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'SEMI_RIMLESS', '', 'half rim', 'half rim', 'en'),
  ('VALUE', 'FRAME_RIM', 'RIMLESS', '', 'sem aro', 'sem aro', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'RIMLESS', '', 'parafusada', 'parafusada', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'RIMLESS', '', 'três peças', 'tres pecas', 'pt-BR'),
  ('VALUE', 'FRAME_RIM', 'RIMLESS', '', 'balgriff', 'balgriff', 'pt-BR'),
  ('VALUE', 'GENDER', 'MASCULINO', '', 'men', 'men', 'pt-BR'),
  ('VALUE', 'GENDER', 'MASCULINO', '', 'mens', 'mens', 'pt-BR'),
  ('VALUE', 'GENDER', 'MASCULINO', '', 'man', 'man', 'pt-BR'),
  ('VALUE', 'GENDER', 'MASCULINO', '', 'male', 'male', 'pt-BR'),
  ('VALUE', 'GENDER', 'MASCULINO', '', 'homem', 'homem', 'pt-BR'),
  ('VALUE', 'GENDER', 'MASCULINO', '', 'hombre', 'hombre', 'pt-BR'),
  ('VALUE', 'GENDER', 'FEMININO', '', 'women', 'women', 'pt-BR'),
  ('VALUE', 'GENDER', 'FEMININO', '', 'womens', 'womens', 'pt-BR'),
  ('VALUE', 'GENDER', 'FEMININO', '', 'woman', 'woman', 'pt-BR'),
  ('VALUE', 'GENDER', 'FEMININO', '', 'female', 'female', 'pt-BR'),
  ('VALUE', 'GENDER', 'FEMININO', '', 'mulher', 'mulher', 'pt-BR'),
  ('VALUE', 'GENDER', 'FEMININO', '', 'mujer', 'mujer', 'pt-BR'),
  ('VALUE', 'GENDER', 'UNISSEX', '', 'unisex', 'unisex', 'pt-BR'),
  ('VALUE', 'GENDER', 'UNISSEX', '', 'all', 'all', 'pt-BR'),
  ('VALUE', 'AGE_GROUP', 'ADULT', '', 'adulto', 'adulto', 'pt-BR'),
  ('VALUE', 'AGE_GROUP', 'ADULT', '', 'men', 'men', 'en'),
  ('VALUE', 'AGE_GROUP', 'ADULT', '', 'women', 'women', 'en'),
  ('VALUE', 'AGE_GROUP', 'TEEN', '', 'juvenil', 'juvenil', 'pt-BR'),
  ('VALUE', 'AGE_GROUP', 'TEEN', '', 'big kids', 'big kids', 'en'),
  ('VALUE', 'AGE_GROUP', 'KIDS', '', 'infantil', 'infantil', 'pt-BR'),
  ('VALUE', 'AGE_GROUP', 'KIDS', '', 'criança', 'crianca', 'pt-BR'),
  ('VALUE', 'AGE_GROUP', 'KIDS', '', 'boys', 'boys', 'en'),
  ('VALUE', 'AGE_GROUP', 'KIDS', '', 'girls', 'girls', 'en'),
  ('VALUE', 'AGE_GROUP', 'KIDS', '', 'little kids', 'little kids', 'en'),
  ('VALUE', 'AGE_GROUP', 'BABY', '', 'bebê', 'bebe', 'pt-BR'),
  ('VALUE', 'AGE_GROUP', 'BABY', '', 'infant', 'infant', 'en'),
  ('VALUE', 'AGE_GROUP', 'BABY', '', 'toddler', 'toddler', 'en');
